aurora-is-near/aurora-engine

- Cargo.toml
- Makefile
- src/lib.rs
- src/parameters.rs
> Put evm-bully specific methods behind feature flag.

- Cargo.lock
- Cargo.toml
Dependencies related to `eth-connector`
> Extend dependencies

- src/sdk.rs
- src/types.rs
Extended SDK. 
Related to eth-connector specific logic.
> Extend sdk for eth-connector

- src/json.rs
- src/lib.rs
- src/sdk.rs
* added json parser (for eth-connector)
* modified panic invocations as unreachable
> JSON parser

- src/connector.rs
- src/fungible_token.rs
Addresses https://github.com/aurora-is-near/aurora-engine/pull/23#discussion_r612751919
> References in fungible token

- Cargo.toml
- src/engine.rs
- src/lib.rs
This adds a faucet with the method `make_it_rain` including improvements tackled that were suggested from the previous PR #37.
Please look and verify, I still am getting used to how we do these but I think this is correct.
Closes: #11
> feat: faucet

- src/engine.rs
- src/lib.rs
- src/map.rs
- src/parameters.rs
- src/precompiles/mod.rs
- src/precompiles/native.rs
- src/sdk.rs
Creates a mapping between NEP141 tokens on NEAR and ERC20 tokens deployed on the EVM.
> Erc20 mapping

- src/storage.rs
This is a bit straight forward. It adds a version prefix (starting from `0x7`, being `V1`) to addresses from the get-go.
We are not starting from `0x0` because `0x0` to `0x6` is already in use by test net and beta net. Of course, we could change it to start from `0x0` on the main net, but that would mean that there is no parity across all networks, which is always ideal and would prevent issues later down the line.
`VersionPrefix` doesn't exist in `KeyPrefix` for the reason that we can continue from `0x7` for any other storage prefixes that we may require. It would just be impossible to recover any current data from the `0x0` -> `0x6` prefixes.
Later this needs to be improved in the following ways:
- Current version from a single source.
- Logic to clean up old keys that are not versioned …
> Add storage version prefix.

- src/storage.rs
Small fix as tests failed due to incorrect lengths of #77.
Thanks @sept-en.
> Fix versioned storage scheme byte lengths.

- src/engine.rs
- src/lib.rs
Implements versioned states which were missed in #77.
Thanks @mfornet.
> Implement versioned states.

- src/lib.rs
Sorry! I do often forget about the bully. Thanks for adding a check for it to CI!
Closes #126
> Fix(bully): compilation

- src/fungible_token.rs
- src/lib.rs
- src/sdk.rs
Fixing as per previous PR comment: https://github.com/aurora-is-near/aurora-engine/pull/109#discussion_r641574473
> Simplify sdk::read_u64 return type

- src/json.rs
Fixes a [clippy warning](https://rust-lang.github.io/rust-clippy/master/index.html#enum_variant_names) (only triggers on nightly, but we run nightly clippy occasionally to catch additional lints).
> Fix clippy::enum_variant_names

- Cargo.lock
- Cargo.toml
- etc/state-migration-test/Cargo.lock
- src/tests/sanity.rs
Related to https://github.com/near/nearcore/issues/4814
> Test counting the number of functions in our wasm contract

- src/tests/res/poster.sol
- src/tests/sanity.rs
Shows that #270 is not an engine issue.
> Test for overriding state

- doc/benchmarks.md
Some documentation about our existing benchmarks. This can help on boarding new people and be used as a reference for external teams interested in our performance characteristics.
> Feat(docs): Benchmark documentation

- engine-sdk/src/env.rs
- engine-sdk/src/error.rs
- engine-sdk/src/lib.rs
- engine-sdk/src/near_runtime.rs
- engine/src/connector.rs
- engine/src/engine.rs
- engine/src/fungible_token.rs
- engine/src/lib.rs
- etc/state-migration-test/src/lib.rs
This is a continuation of the effort to reactor the engine to not depend on NEAR host functions (which is necessary for the standalone engine). It depends on the previous PRs #342 #346 #347 being merged first.
> Factor out blockchain environment variable access as a trait

- engine/src/fungible_token.rs
- engine/src/parameters.rs
Addressing comments from https://github.com/aurora-is-near/aurora-engine/pull/355#pullrequestreview-810170618
> Minor fixes to sdk refactor

- engine/src/lib.rs
Add in logging which will help transaction debugging for gas costs
> Additional log data for Submit

- Cargo.lock
- engine-tests/Cargo.toml
- engine-tests/src/benches/nft_pagination.rs
- engine-tests/src/test_utils/mocked_external.rs
- engine-tests/src/test_utils/mod.rs
- engine-tests/src/tests/erc20_connector.rs
> chore: upgrade to the latest nearcore version

- README.md
This was found by @mooori while running tests for first time.
> Add docker as a prerequisites

- Cargo.lock
- Cargo.toml
- engine-tests/src/tests/repro.rs
- etc/self-contained-5bEgfRQ/Cargo.lock
It should fix dependabot-related issues.
> Cargo dependency update

- Cargo.lock
- engine-precompiles/Cargo.toml
- engine-sdk/Cargo.toml
- engine-standalone-storage/Cargo.toml
- engine-tests/Cargo.toml
- engine-types/Cargo.toml
- engine/Cargo.toml
- etc/self-contained-5bEgfRQ/Cargo.toml
- etc/state-migration-test/Cargo.lock
- etc/state-migration-test/Cargo.toml
- etc/xcc-router/Cargo.lock
- etc/xcc-router/Cargo.toml
- etc/xcc-router/src/lib.rs
- etc/xcc-router/src/tests.rs
The recent version of near-sdk addresses makes the Router Contract cleaner IMO.
> User version 4.0.0 of near-sdk-rs

- Cargo.lock
- engine-precompiles/Cargo.toml
- engine-sdk/Cargo.toml
- engine-tests/Cargo.toml
- engine-types/Cargo.toml
- engine/Cargo.toml
This simply updates all the rust crypto libraries to their latest counterparts. Notably, from v0.9 -> v0.10.
Ripemd160 was done separately as the library had been deprecated. See https://github.com/aurora-is-near/aurora-engine/pull/570.
We may see a slight gain in performance, but our gas tests do not indicate it to be large.
None.
Check that this is being updated to the latest.
None.
> Chore: Update Rust crypto libraries

- Cargo.lock
- engine-precompiles/Cargo.toml
- engine-precompiles/src/hash.rs
While updating the other rust-crypto libraries, I noticed that the `ripemd160` library was deprecated in favour of `ripemd` library. This simply switches to the new library.
None.
None.
Note that the deprecation notice came from the following search: https://lib.rs/search?q=ripemd160.
None.
> Chore(Precompiles): Ripemd160 lib deprecated

- .github/workflows/builds.yml
This on-push build job was faulty and was using an old version of the `cargo make` jobs. Likewise, it is unnecessary to build the test and bully binaries.
None.
None.
The work should be verified following this documentation for [matrixes](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs) and how to use [upload-release-action](https://github.com/svenstaro/upload-release-action).
What is supposed to happen is that both the testnet and mainnet wasm files are uploaded with a latest release.
None.
> Fix: Make binaries on push

- doc/eth-connector.md
Added extended documentation for Eth Connector logic.
> [Docs] Eth Connector - extended documentation

- engine-types/src/account_id.rs
- engine-types/src/types/wei.rs
- engine/src/parameters.rs
In order to allow for external libraries to easily JSON serialise some parameter structs, this simply adds serde deserialize and serialize to those structs.
None.
None.
Check and ensure that no other parameters are used in lib.rs, particularly those that implement `TryFrom<JsonValue>`.
Required for aurora-workspaces.
> feat: add serde JSON to JSON serializable structs in parameters

- .github/workflows/tests.yml
- Cargo.lock
- engine-precompiles/Cargo.toml
- engine-sdk/src/lib.rs
- engine-types/Cargo.toml
- engine/src/connector.rs
- engine/src/engine.rs
- engine/src/fungible_token.rs
The PR adds some improvements in `log` marcro.
Pay attention to usage of `format_args!` macro in `log` macro implementation.
> Improvements in log macro

- README.md
The README currently displays out of date information about the current Rust version which we use. This simply removes that detail as it is no longer needed as its handled by the toolchain file automatically.
Make sure that there are no other redundant details in the README.
> Update README to exclude pre-req of installing specific Rust version

- Cargo.lock
- engine-precompiles/Cargo.toml
- engine-standalone-storage/Cargo.toml
- engine-standalone-tracing/Cargo.toml
- engine-test-doubles/Cargo.toml
- engine-tests/Cargo.toml
- engine-transactions/Cargo.toml
- engine-types/Cargo.toml
- engine/Cargo.toml
- etc/xcc-router/Cargo.lock
Includes some overflow-related fixes.
Existing tests.
> Chore: Update to SputnikVM version v0.37.1-aurora

- Cargo.lock
- engine-precompiles/Cargo.toml
- engine-standalone-storage/Cargo.toml
- engine-standalone-tracing/Cargo.toml
- engine-test-doubles/Cargo.toml
- engine-tests/Cargo.toml
- engine-tests/src/tests/one_inch.rs
- engine-tests/src/tests/repro.rs
- engine-tests/src/tests/uniswap.rs
- engine-transactions/Cargo.toml
- engine/Cargo.toml
Updates to SputnikVM `v0.37.2-aurora`, which includes some performance improvements.
Provides about a 5% reduction in Aurora Engine gas usage.
Existing tests.
> Chore: Update to SputnikVM `v0.37.2-aurora`

- Cargo.lock
- engine/Cargo.toml
- engine/src/engine.rs
Adds an utility function to create legacy addresses from a caller address and a nonce. We want to use this on the refiner to populate contract addresses.
I founded an almost identical function in the tests on engine/src/engine.rs so I remove it and keep only the new public one. The function uses the aurora_engine_sdk keccak function and not directly the one from sha3 crate, so I remove it from the dev dependencies. 
Ran all the tests and added a new one targeting the new function.
I would like you to give me feedback about rust coding. If you see anything that is wrong or if you think there is another way of doing things that is more elegant or common, pls let me know.
> create legacy address function

- etc/eth-contracts/.solhint.json
- etc/eth-contracts/.solhintignore
- etc/eth-contracts/package.json
- etc/eth-contracts/yarn.lock
> Chore: switch to solhint linter

- engine-standalone-storage/src/lib.rs
- engine-standalone-storage/src/relayer_db/mod.rs
- engine-standalone-storage/src/relayer_db/types.rs
The PR removes usage of `as` conversions in the `engine-standalone-storage` crate.
> chore: fix security audit check

- etc/eth-contracts/package.json
- etc/eth-contracts/yarn.lock
Fixes dependabot issue [108](https://github.com/aurora-is-near/aurora-engine/security/dependabot/108) [124](https://github.com/aurora-is-near/aurora-engine/security/dependabot/124) and  all happening at path `/etc/xcc-router/Cargo.lock`. 
If near gas cost changes from changing dependancies, it will appear in the CI.
Run dependabot on this branch and issue 124 should be removed.
Run dependabot on this branch and issue 124 should be removed.
> Fix dependabot issue #108,#124

- engine-precompiles/src/lib.rs
- engine-transactions/src/lib.rs
- engine-types/src/lib.rs
- rust-toolchain
The PR attempts to remove unused `cfg_attr` attributes preventing the use of dependencies with stable rust.
> chore: remove unused cfg_attr attributes

- engine-precompiles/src/native.rs
- engine-precompiles/src/promise_result.rs
- engine-precompiles/src/secp256k1.rs
- engine-precompiles/src/xcc.rs
- engine-sdk/src/types.rs
- engine-types/src/types/gas.rs
- engine/src/connector.rs
- engine/src/deposit_event.rs
- engine/src/engine.rs
- engine/src/lib.rs
This PR covers some minor issues:
- Use `checked_add()`, `checked_sub()`checked_mul()` where it is possible
-  Avoiding use of  `unwrap()`.
- Fixing inaccurate comments, some typos and outdated comments.
> Fix: miscellaneous minor issues

- Cargo.lock
- engine-tests/src/tests/one_inch.rs
- engine-tests/src/tests/repro.rs
- engine-tests/src/tests/uniswap.rs
The PR updates the transitive dependency `sha3` to 0.10.8, which fixes the regression in gas costs (in the tests) regarding this [fix](https://github.com/RustCrypto/hashes/pull/472).  
A tiny gas costs improvement.
> chore: update transitive dependency sha3 to 0.10.8

- Cargo.lock
- engine-precompiles/Cargo.toml
- engine-precompiles/src/lib.rs
- engine-standalone-storage/Cargo.toml
- engine-standalone-tracing/Cargo.toml
- engine-test-doubles/Cargo.toml
- engine-tests/Cargo.toml
- engine-tests/src/test_utils/solidity.rs
- engine-transactions/Cargo.toml
- engine/Cargo.toml
- engine/src/engine.rs
Adds Shanghai hardfork support by integrating updated aurora-sputnikvm.
N/A
Testing has been added to sputnikvm's test suite. All engine tests are passing.
The majority of changes are in sputnikvm which have already been reviewed.
N/A
> feat: shanghai hf support

- Cargo.lock
- engine-modexp/src/lib.rs
- engine-precompiles/src/lib.rs
- engine-precompiles/src/modexp.rs
- engine-standalone-storage/Cargo.toml
- engine-standalone-storage/src/sync/mod.rs
- engine-tests/Cargo.toml
- engine-tests/src/test_utils/standalone/mocks/mod.rs
- engine-tests/src/test_utils/standalone/mod.rs
- engine-tests/src/tests/standalone/call_tracer.rs
- engine-tests/src/tests/standalone/sanity.rs
- engine-tests/src/tests/standalone/sync.rs
- engine/Cargo.toml
- engine/src/connector.rs
- engine/src/engine.rs
- engine/src/lib.rs
The PR is alternative version of #769.
> feat(precompiles): generic modexp algorithm

- engine/.catalog-info.yaml
> chore(backstage): add testnet address

- .github/workflows/scheduled_lints.yml
The PR fixes the broken scheduled CI task. The master has been chosen as a base branch intentionally.
> chore: fix scheduled CI task

- .github/workflows/builds.yml
The PR modifies the build script for CI. After these changes builds will be created after pushing a new tag.
> feat(ci): create release builds after pushing tag

- .github/workflows/builds.yml
One more attempt to fix the CI script for the publishing release.
> chore: fix CI script for publishing release

- engine/src/lib.rs
The PR adds the contract status check for key management functions.
> chore: add contract running check for key management function

- .github/CODEOWNERS
- Cargo.lock
> Chore: cleanup Codeowners

- README.md
This PR adds the lang guards to the README for code formatting and highlighting
> chore: add lang guard to README

- scripts/build-neard-sandbox.sh
The PR fixes a path to the `neard-sandbox` in the schedule CI script.
> ci: fix path to neard-sandbox

- .github/workflows/scheduled_lints.yml
The PR decreases the number of parallel tasks in scheduled action in the CI, which is executed on the self-hoted runner.
> ci: decrease amount of parallel tasks in schedule CI

- .gitignore
- etc/eth-contracts/README.md
- etc/eth-contracts/hardhat.config.js
- etc/eth-contracts/package.json
- etc/eth-contracts/yarn.lock
This PR modifies `hardhat.config.js` to support contract verification on a desired network. It also includes README.md that describes all necessary steps.
This does not affect performance or gas usage since it does not introduce any changes to the engine
Just follow steps described in README.md
> Modifying hardhat.config.js to support contract verification

- Cargo.lock
- Cargo.toml
- engine-precompiles/src/lib.rs
- engine-tests/src/tests/repro.rs
🚀  Updated SputnikVM (EVM) to `v0.46.1-aurora`
For some tests gas costs decreased.
> Chore: Update SputnikVM to v0.46.1-aurora

- .github/workflows/scheduled_lints.yml
- scripts/build-neard-sandbox.sh
The PR changes the github runner to the self-hosted runner.
> ci: use self-hosted runner in scheduled task

- .github/workflows/scheduled_lints.yml
- scripts/build-neard-sandbox.sh
Change self-hosted runner in scheduled task to the `github-hosted-heavy-runner`.
> ci: fix scheduled task by changing self hosted runner

- doc/benchmarks.md
This file is missing it's language fences
> chore: add missing language fences

- engine-transactions/.catalog-info.yaml
- engine/.catalog-info.yaml
- etc/tests/.catalog-info.yaml
PR updates `.catalog-info.yaml` files so that they comply with spec by having unique entity names
N/A
N/A
Double check entity names reflect their role in the repo's context.
N/A
> chore: update catalog info

- Cargo.lock
- Cargo.toml
- Makefile.toml
- engine-tests-connector/Cargo.toml
- engine-tests-connector/src/connector.rs
- engine-tests-connector/src/utils.rs
- engine-tests/Cargo.toml
- engine-tests/src/tests/erc20_connector.rs
- engine-tests/src/tests/erc20_mirror.rs
- engine-tests/src/tests/repro.rs
- engine-tests/src/utils/workspace.rs
- engine-workspace/src/contract.rs
- engine-workspace/src/lib.rs
- engine/src/contract_methods/connector/external.rs
- engine/src/contract_methods/connector/mod.rs
- etc/tests/fibonacci/Cargo.toml
- etc/tests/mock-controller/Cargo.toml
- etc/tests/mock-controller/src/lib.rs
The PR applies changes regarding the new API of the eth connector contract.
Tiny changes.
Related tests have been modified.
> feat: use omni compatible eth connector
