src/meta_parsing.rs
src/parameters.rs
src/types.rs
tests/test_meta_parsing.rs

This was a bit of a pain to fix. I assumed the wrong parts of it were broken initially. After much frusteration and pulling my hair out and reading and re-reading ETH documentation, I knew full well about the extra byte and had assumed that certainly had to do with it. Finally, had an epiphany which helped progress. Unfortunately it was still failing. That was because of a new addition that I added which I originally thought would be part of the solution. There were two minor fixes that had solved this issue. Mostly, positioning of that extra byte. It just was not entirely obvious initially. The good news is that I feel quite well versed with ecrecovery now.

fix meta parsing test

---

Makefile

* `make check` includes running tests, running `clippy`, checking the code formatting
* `make test` depends on release since it needs the `release.wasm` artifact

Fix: Makefile

---

.github/workflows/scheduled_lints.yml

@joshuajbouw pointed out that there is value in running the nightly clippy, not just the one for our fixed toolchain, because there are new lints being added. This PR adds a regularly scheduled GitHub action to run nightly clippy. The reason to make it run on a schedule instead of modifying the lints which run on pushes/PRs is because we don't want failures to randomly happen if there is a new lint which flags code that was not changed by the commit/PR. The reason to make it run at a strange time (instead of on an hour or half hour) is to avoid congestion in the GitHub actions infrastructure.

Add twice weekly run of nightly clippy

---

.github/workflows/lints.yml
.github/workflows/scheduled_lints.yml
Makefile
src/engine.rs
src/lib.rs

Previously `clippy` was not being used to check code gated behind the `contract` feature flag. I assume this is because it was failing due to the presence of `on_panic` and `on_alloc_error`. However, we can only include those functions when we compile to wasm, then `clippy` will work with the `contract` feature flag.
In this PR we change the Makefile and CI to have `clippy` check the code with the `contract` feature enabled (and with no-std since that is how we compile the contract).
`clippy` found one error in `engine.rs` and two in `lib.rs`. These are also corrected in this PR.

Fix: Use clippy on contract code too

---

src/connector.rs
src/parameters.rs
src/prover.rs
src/types.rs

Clippy reports many errors like the following:
```
error: use of `expect` followed by a function call
--> src/prover.rs:143:14
|
143 |             .expect(str_from_slice(FAILED_PARSE));
|              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try this: `unwrap_or_else(|_| { panic!("{}", str_from_slice(FAILED_PARSE).to_string()) })`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#expect_fun_call
```
This PR corrects all those errors by using a new trait on `Option` and `Result` that can take an expect message in bytes.

Fix: clippy errors in eth-connector

---

src/engine.rs
src/lib.rs

Quite simply, adds a method, `transfer`, to transfer a balance from one to another to the `Engine`.
Comes with additional added methods which will allow others to easily increase or decrease a balance, `increase_balance` and `decrease_balance`.
Closes #35.

feat: add `transfer` method to engine

---

README.md

Should be merged after https://github.com/near/docs/pull/649 has been merged.

Link to NEAR docs in README.

---

src/engine.rs

Really straight forward, `max_value` was flagged as deprecated, this changes it to the suggested new `const MAX`.

chore: change deprecated `u64::max_value` to `u64::MAX`

---

src/lib.rs

Really small quality of life improvement which will just simply return the error messages contained in `Custom` option.

feat: return formatted custom messages

---

src/lib.rs
src/parameters.rs
src/types.rs

Implement necessary contract method `begin_chain` for `evm-bully`.

---

src/engine.rs
src/lib.rs
src/types.rs

To prevent replaying transactions, we need to check the nonce matches the nonce of the account, and increment it if it matches.
In the case of directly calling `call` or `deploy_code` replaying the transaction is not a concern because it originates from Near, and so is protected by the base system, but I still increment the nonce in those cases to be consistent.
One issue with this is the case where the transaction runs out of Near gas. In that case the state changes are rolled back, including the incremented nonce, which is different behaviour from if the transaction ran on Ethereum directly. I think the best way to handle this would be to make running out of Near gas impossible by setting appropriate limits on the Eth gas. But this probably is not feasible in the short term. We might …

Feat: Check and increment nonce

---

src/precompiles/hash.rs
src/precompiles/modexp.rs

Fixes two small issues with the precompiles:
1. In RIPEMD160 the result needs to be padded out to 32 bytes
2. In modexp the result needs to be padded out to the same length as the modulus

Fix Precompiles: RIPEMD160, modexp

---

src/engine.rs
src/parameters.rs

This is pretty short, I reviewed the code for the backend implementation and checked and diagnosed where we may have issues. The only real issue that I had found is that we likely have an issue if the `gas_limit` returns 0. This was changed to max value and docs were added in. The other change is the `block_coinbase` returning the first 2^160 of the keccak256 hash of `aurora`.

fix: gas_limit

---

src/engine.rs
src/lib.rs
src/meta_parsing.rs
src/precompiles/blake2.rs
src/precompiles/bn128.rs
src/prelude.rs
src/types.rs

This PR came out out of this issue outlined here: https://github.com/aurora-is-near/aurora-engine/pull/48#discussion_r624676151.
Do note, that this PR may look intimidating with amount of files changed + lines, but most of it is refactoring.
This is in general just a much better error structure. I really hated how the underlying EVM for some bizarre reason mixed together BOTH result types. It just can be awkward to work with in general. That is fixed with this PR.
As a bonus, all error returns are now all consistent too as `ERR_`.
Point of discussion: As far as I'm aware, Reverts shouldn't be considered an "ERR" as they are part of everyday EVM life? As in, the contract executes correctly, but due to some circumstance, it'll back out without actually applying changes.
Closes: …

feat: Better errors

---

src/transaction.rs

This is an issue that came up during discovering a problem that @artob  found when decoding an RLP encoded signed transaction.

Fix transaction decoding

---

Cargo.toml
src/connector.rs
src/engine.rs
src/fungible_token.rs
src/lib.rs
src/parameters.rs
src/prelude.rs
src/storage.rs
src/test_utils/mod.rs

There are a few things here:
1. A call to `new` is not enough to initialize the Aurora engine contract anymore, an eth-connector instance is also required (because it is used in the `ApplyBackend` implementation). This makes me wonder if they should be separate calls in the first place. In the tests I now create an eth-connector.
2. As mentioned above, the `ApplyBackend` implementation uses a eth-connector function to update balances (this is to make sure the connector does not fall out of sync with the base engine). However, the structure passed to `apply` contains the actual new balance, not the change in balance. Therefore, the deposit call was incorrect, and instead it needs to be a set balance call. I have implemented that to fix the bug.
3. We decided that having an Aurora native …

Fix sanity tests in connector

---

src/engine.rs
src/lib.rs
src/meta_parsing.rs
src/sdk.rs
src/storage.rs
src/types.rs

I've decided to comment inline.
Overall I didn't find anything major. I think the biggest issue is `remove_all_storage`. This is a protocol level decision that led to the removal of prefix deletion or iterations. The recent protocol change also restricted account deletion if the storage usage exceeds 10Kb (beyond the contract). This is done to prevent key iteration.
```rust
/// Removes all storage for the given address.
pub fn remove_all_storage(_address: &Address) {
// FIXME: there is presently no way to prefix delete trie state.
// NOTE: There is not going to be a method on runtime for this.
//     You may need to store all keys in a list if you want to do this in a contract.
//     Maybe you can incentivize people to delete dead old keys. They can observe them from
//     external …
```

Eugene audit 2021 05 11

---

Cargo.lock
Cargo.toml

This is an emergency Sputnik EVM update as per [RUSTSEC-2021-0066](https://rustsec.org/advisories/RUSTSEC-2021-0066.html).

Update evm-core to 0.26.1

---

Cargo.lock
Cargo.toml

Just in case someone accidentally downgrades the `evm-core` as it is not explicitly directly used, we can specify the version in the cargo manifest to ensure we are using it. This wouldn't be needed if `evm` was updated to 0.26.1 as well.

Explicitly use `evm-core` 0.26.1.

---

src/storage.rs

This code is not needed, so let's not have it.

Remove unused VersionPrefixU8

---

src/precompiles/mod.rs
src/precompiles/native.rs
src/prelude.rs
src/sdk.rs
src/types.rs

Add precompiles, so eth-connector and erc20-connector can work from it.

Base precompile code between connectors

---

src/test_utils/mod.rs

In #84 Marcelo encountered an error due to underflow resulting from releasing storage that was not properly tracked. This PR fixes that issue.
Note: the issue is only in the testing framework, it does not impact any production code.

Fix(tests): Track storage usage in AuroraRunner

---

.github/workflows/tests.yml

Closes #91 
Hopefully this works. It'll be a little difficult to test because it will only help future PRs (not this one since this one will create the cache I think). Currently the tests take ~20 minutes to run ([example](https://github.com/aurora-is-near/aurora-engine/runs/2578076872)), so we'll have to see if this time goes down.
Workflow based on the [official `cache` action documentation](https://github.com/actions/cache/blob/main/examples.md#rust---cargo).

Use cache action to save cargo artifacts between runs

---

src/engine.rs
src/lib.rs
src/meta_parsing.rs
src/sdk.rs

Closes https://github.com/aurora-is-near/aurora-engine/issues/76
Addresses most of the minor TODOs from #74 
One still remains, but I'm unsure how to address it. I've [reached out for clarification](https://github.com/aurora-is-near/aurora-engine/pull/74#discussion_r632025663). That last one can be done as a separate PR.

Address comments from Audit

---

.github/workflows/tests.yml

Some low-hanging fruit to reduce the size of the CI cache, as suggested in https://github.com/aurora-is-near/aurora-engine/pull/92#issuecomment-843087788

Reduce size of cargo cache in CI

---

src/benches/eth_deploy_code.rs
src/benches/eth_erc20.rs
src/benches/eth_standard_precompiles.rs
src/benches/eth_transfer.rs
src/engine.rs
src/lib.rs
src/meta_parsing.rs
src/prelude.rs
src/test_utils/mod.rs
src/tests/erc20.rs
src/tests/sanity.rs
src/tests/standard_precompiles.rs
src/transaction.rs
src/types.rs
tests/test_meta_parsing.rs

Closes #67 
This is a very safe refactoring since it does not change any functionality. But it is important because it will hopefully prevent us from making silly mistakes in the future when it comes to working with balances.
Notably this probably may impact the eth-connector work. Since that work is higher priority it might make sense to merge it first, then rebase this PR. On the other hand, if there is time to merge this first and then rebase the eth-connector work, then maybe that would be valuable as it may catch simple mistakes in that important work (if there are any).

Newtype for amounts in Wei

---

src/lib.rs

In recent refactoring I forgot to compile with the evm-bully flag, so I missed a couple things. This PR corrects what I missed so that the bully code compiles again.

Fix(evm-bully): Fixes after recent refactoring

---

src/engine.rs
src/lib.rs

As pointed out by @joshuajbouw `Engine::get_state` returning a default value when the state is missing could obscure some critical issue if a state migration goes wrong. In this PR we refactor the function to return a `Result` with clear errors.
In future PRs we will address the broader issue of state migration, but this refactor seemed large enough to be done separately, before new code is added.

Refactor Engine::get_state

---

.github/workflows/tests.yml

At the moment, running `cargo check` locally for me:
* fails with some compilation error in the dependency
* updates Cargo.lock
That is, the Cargo.lock that is committed into the repo doesn't work. To
prevent this from happening in the future, let's forbid CI from
upgrading Cargo.lock.
Previously: https://github.com/aurora-is-near/aurora-engine/pull/93

Ensure that Cargo.lock in the repo is valid

---

src/lib.rs
src/sdk.rs

On wasm, intrinsic for trap unreachable is stable and exposed via
`core::arch`, no need for a nightly feature.
Previously: https://github.com/aurora-is-near/aurora-engine/pull/94

Remove unneeded nightly feature

---

src/connector.rs
src/fungible_token.rs
src/lib.rs
src/storage.rs
tests/test_connector.rs

Calculate total unique accounts.
Added method:
* get_accounts_counter
Covered with test

Eth connector statistic

---

Cargo.lock
Cargo.toml
src/connector.rs
src/fungible_token.rs
src/json.rs
src/lib.rs
src/parameters.rs
src/precompiles/native.rs
src/prelude.rs
src/storage.rs
tests/test_connector.rs

I didn't fully understand the flow. But here are a few findings:
- Use JSON instead of Borsh for FT standard methods. Since the goal is to be compatible with the rest of NEAR ecosystem with fungible tokens, this change has to use JSON as an input and output for methods like `ft_transfer` and `ft_transfer_call`, as well as view methods like `ft_balance_of`.
- I'm not sure if the internal `ft_transfer_call` is correctly addressing the balance and doesn't the rollback.
- It's very confusing to bundle NEAR and ETH into one FungibleToken struct. It probably worth to use 2 of them, but then have unified implementation. There is also a proposal for a multi-fungible token standard, but it's not on paper.
- I've commented in the code for the issues I found. 
- Also sorry for renaming …

Eugene's Eth connector review

---

src/precompiles/blake2.rs
src/precompiles/bn128.rs
src/precompiles/hash.rs
src/precompiles/identity.rs
src/precompiles/mod.rs
src/precompiles/modexp.rs
src/precompiles/native.rs
src/precompiles/secp256k1.rs

Fix(precompiles): Match on full address when dispatching on precompiles

---

src/connector.rs
src/lib.rs
src/parameters.rs

* Add `set_eth_connector_contract_data()` method.
* Minor refactoring: `init_contract()` method now accepts `InitCallArgs`
instead of making IO operations in it.

Eth-connector: add the way to set contract data. Minor refactoring.

---

Cargo.lock
Cargo.toml
etc/state-migration-test/Cargo.lock
src/meta_parsing.rs

We do not want to depend on Lunarity any more because it uses a difference license than the rest of our project. It also doesn't compile on latest nightly because it depends on an old version of Logos.
In this PR we remove the dependency on Lunarity and instead  depend on (the most recent version of) Logos directly. This required adding a bit more code to `meta_parsing` because we were using Lunarity for parsing the type strings. I think the new code is a little better than the old code anyway because the state machine is a little simpler as the array bracket parsing can be delegated to the lexer.
With this change the project now compiles under latest nightly, though `cargo +nightly clippy` doesn't pass yet because there are some errors. I'll fix those in a follow-up PR.
Closes #34

Remove dependency on Lunarity

---

src/types.rs

Running `cargo +nightly clippy --no-default-features --features=contract,log -- -D warnings` gives
```
error: methods with the following characteristics: (`to_*` and `self` type is `Copy`) usually take `self` by value
--> src/types.rs:48:21
|
48 |     pub fn to_bytes(&self) -> [u8; 32] {
|                     ^^^^^
|
= note: `-D clippy::wrong-self-convention` implied by `-D warnings`
= help: consider choosing a less ambiguous name
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#wrong_self_convention
error: aborting due to previous error
error: could not compile `aurora-engine`
```
This PR fixes the issue. The project should now pass `clippy` on latest nightly! 🎉

Fix: nightly clippy checks

---

.github/workflows/tests.yml

The contract build for the evm-bully (`make evm-bully=yes`) often breaks.
Add it to CI to prevent that from happening.

Add evm-bully=yes build to CI

---

src/engine.rs
src/lib.rs
src/test_utils/erc20.rs
src/test_utils/mod.rs
src/test_utils/standard_precompiles.rs
src/tests/erc20.rs
src/tests/sanity.rs
src/transaction.rs

Fix(engine): handle transaction gas limit properly

---

Cargo.lock
Cargo.toml
etc/state-migration-test/Cargo.lock
src/precompiles/blake2.rs
src/precompiles/bn128.rs
src/precompiles/hash.rs
src/precompiles/identity.rs
src/precompiles/mod.rs
src/precompiles/modexp.rs
src/precompiles/native.rs
src/precompiles/secp256k1.rs

This updates the Aurora engine to the latest `evm-core`.
Do note that the merge to `master` is intentional given the nature of this update.
This also does include the logs which @mfornet had added to upstream so a further PR should be created to utilise logs.

Update to `evm_core` 0.27.1

---

src/connector.rs
src/engine.rs
src/lib.rs
src/meta_parsing.rs
src/precompiles/modexp.rs

Clippy (on latest nightly) pointed out several places where we were borrowing for no reason. This PR could also be called "remove a bunch of useless ampersands from the code" since no functionality is changed.

Fix needless borrows

---

src/json.rs
src/lib.rs
src/parameters.rs
src/types.rs

* Add `JsonError` for `json` module.
* Use `JsonError` instead `()` for errors in `JsonValue`.
* Don't panic in `json` module on parsing.
* Move `SdkUnwrap`, `SdkExpect` traits from `lib.rs` to `types.rs`.
* Unwrap the error when parsing JSON for parameter args instead of failing with generic `ERR_FAILED_PARSE`.

Add JSON custom error types. Refactoring.

---

src/connector.rs
tests/test_connector.rs

We used to have the following workflow for depositing ETH to Aurora:
* Deposit nETH (NEP-141) tokens to Aurora account
* Burn Aurora's nETH tokens
* Mint ETH to Ethereum address on Aurora.
When we call `exitToNear` precompile for ETH, we expect to burn ETH on Aurora and make `ft_transfer` of nETH tokens from Aurora to the recipient on NEAR. The problem using the previously mentioned deposit workflow is that we don't have nETH tokens available on Aurora account when we try to perform this exit.
Possible solutions:
This solution is currently implemented in the PR. 
Pros: 
* We have needed liquidity and keep calling just a regular  `ft_transfer` when calling `exitToNear` precompile for ETH.
* We have consistency with the approach that we use for ERC20 connector for Aurora (User transfers …

EthConnector: don't burn NEP-141 on deposit.

---

src/connector.rs
src/fungible_token.rs
src/lib.rs
src/prover.rs
src/sdk.rs

Addresses https://github.com/aurora-is-near/aurora-engine/pull/51#discussion_r647823241
I'm always happen when a PR can remove more lines of code than it adds :)

Macro for logging

---

src/connector.rs

Minor change. Main benefit is removing an `unwrap`.

Fix clippy::unnecessary_unwrap

---

src/deposit_event.rs
src/fungible_token.rs
src/parameters.rs
src/precompiles/blake2.rs
src/precompiles/bn128.rs
src/precompiles/hash.rs
src/precompiles/identity.rs
src/precompiles/mod.rs
src/precompiles/modexp.rs
src/precompiles/native.rs
src/precompiles/secp256k1.rs
src/test_utils/exit_precompile.rs
src/tests/contract_call.rs
src/tests/erc20_connector.rs
src/tests/sanity.rs
src/types.rs
tests/test_meta_parsing.rs

The purpose of PR is to fix all warnings we currently have.
For some constants it was weird to add an unnecessary `engine` feature check, so I decided to manually turn off the warning by using the following approach:
```rust
#[cfg_attr(not(feature = "engine"), allow(dead_code))]
```

Fix warnings

---

src/fungible_token.rs

I cannot take my ETH from my Aurora address and exit to my NEAR account. I get the error `Smart contract panicked: ERR_ACCOUNT_NOT_EXIST`. This is because my account has never held ETH before, but I think I should still be able to send it there.
See https://explorer.testnet.near.org/transactions/91qBTPUe7iA7qzDzbivJgmkv3DEYJKdVTqL9JsRRyeH6 for full transaction log.
This PR removes the panic, and thus should fix the issue. I wanted to write a test to prove that (a) this was the problem and (b) this fixes it, but writing such a test turned out to be much much harder than the solution (this is a problem itself; tests should be easy to write because then we will actually write them!). So I decided to submit this fix first and the test later because I think the fix is very high priority.

Fix(ExitToNear): register the receiver account if it does not exist

---

etc/eth-contracts/contracts/EvmErc20.sol

The used [ERC-20 v4.1.0](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/release-v4.1/contracts/token/ERC20/ERC20.sol#L7) already imports the `context.sol` contract. 
Also the EvmERC20 does not follow the openzeppling `msgSender` style.

Remove duplicate import of the context contract

---

src/types.rs

The EVM uses big-endian, WebAssembly uses little-endian encoding.
See discussions on #30 and #122.

Properly document endianess.

---

src/connector.rs
src/engine.rs
src/fungible_token.rs
src/json.rs
src/tests/erc20_connector.rs

Return number as json (string) in ft_on_transfer

Fix NEP-141 Compliance

---

Makefile

I noticed that we still compile test-build without specifying `mainnet` feature that we recently added. Right now `mainnet` feature doesn't have any more features enabled, still I think we need this for consistency, so if new dependency features are added, we never miss them and always run tests on close to the production feature set.
Later we may even add 3 separate build configurations for tests running with `mainnet`, `testnet`, `betanet` features.

Tests: always compile with `mainnet` feature enabled.

---

.github/workflows/scheduled_lints.yml
src/precompiles/modexp.rs

The [scheduled run of nightly clippy was broken](https://github.com/aurora-is-near/aurora-engine/runs/2902922641?check_suite_focus=true). If it would have run it would have also found two more needless borrows, so those are fixed here too.

Fix(engine): Fix scheduled nightly clippy

---

src/lib.rs
src/test_utils/erc20.rs
src/test_utils/exit_precompile.rs
src/test_utils/mod.rs
src/test_utils/self_destruct.rs
src/test_utils/standard_precompiles.rs
src/tests/erc20_connector.rs
src/tests/sanity.rs
src/transaction.rs

EIP-2718 is required for the Berlin HardFork.
Spec: https://eips.ethereum.org/EIPS/eip-2718
This change is pretty minimal because it doesn't specify any new transaction types, only the format that new types will use. For example, when we add EIP-2930 support then we will add a new variant to the `EthTransaction` enum introduced in this PR.

EIP-2718: Typed Transaction Envelope support

---

etc/eth-contracts/hardhat.config.js
etc/eth-contracts/package.json
etc/eth-contracts/tasks/storage.js
etc/eth-contracts/yarn.lock

Adding a hardhat plugin that allow developer to generate the storage layout for solidity contract. These `storage slots` are used for updating the state variables in any adminControlled inheriting contract.
```
npx hardhat storageLayout
┌─────────────────┬────────────────┬──────────────┬────────┬─────────────────────────────────────────────────────┐
│ contract        │ state_variable │ storage_slot │ offset │ type                                                │
├─────────────────┼────────────────┼──────────────┼────────┼─────────────────────────────────────────────────────┤
│ ERC20           │ _balances      │      0       │   0    │ t_mapping(t_address,t_uint256)                      │
│ ERC20           │ _allowances    │      1       │   0    │ …
```

feat: storage layout for EvmErc20.sol

---

src/engine.rs
src/parameters.rs
src/precompiles/blake2.rs
src/precompiles/bn128.rs
src/precompiles/hash.rs
src/precompiles/identity.rs
src/precompiles/mod.rs
src/precompiles/modexp.rs
src/precompiles/native.rs
src/precompiles/secp256k1.rs
src/prelude.rs
src/test_utils/mod.rs

This is a bit of a catch-all and will have solutions to outstanding problems that I have been aware of but hadn't realised that it will meet its limitations now.
This is intended to be added to the `develop` branch after https://github.com/aurora-is-near/aurora-engine/pull/181. It just kept growing until it virtually refactored all of the precompile library.
Shortlist of changes:
* Removes the state generic from everything
* Reduces and implies a lot of the code. Code reduction of around 325 lines.
* Easier to read
* No duplicate code

EIP-2930 refactor and extra changes

---

.github/workflows/tests.yml

- Remove default caching mechanism. Contents of `~/.cargo` are now shared across runs since all runners are now on the same machine. Caching of `target` directory using remote storage is not efficient and can be implemented faster as written below.
- Wrap Rust compiler with [sccache](https://github.com/mozilla/sccache), which partly allows to reuse compiled dependencies ([it's also mentioned here](https://doc.rust-lang.org/cargo/guide/build-cache.html)). Currently, there are 481mb of cache-hittable artifacts.
- Share `target/debug` and `target/release` across runs. This allows profits even on partial cache-hit from previous builds + saves a lot of disk space for us :)

Speed up workflow build caching

---

.github/workflows/builds.yml
.github/workflows/lints.yml
.github/workflows/scheduled_lints.yml
.github/workflows/tests.yml

Makes no sense after migrating to self-hosted runner (local runtime already have this toolchain).
Furthermore, it creates unwanted data-races

Remove rust toolchain installation in workflow

---

.github/workflows/tests.yml
Makefile

With new changes to have tests run with different feature flags, we should run all tests in CI.

Run all tests for all networks in CI

---

.github/workflows/tests.yml
Cargo.toml

Benchmarks show that this significantly reduces gas usage (around 47%) for non-trivial contracts (e.g. uniswap). We have a larger binary as a result (678K -> 865K on my machine), but I think it is worthwhile.

Optimize for performance instead of code size

---

.github/workflows/tests.yml

- Parallelize tests using [strategy.matrix](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix)
- Fix issue with data race (copy target parts instead of symlinking). `target/release` and `target/debug` are not actually concurrency-safe, my bad

Parallelize test suits

---

.github/workflows/tests.yml

Implement same thing that we had with [actions/cache](https://github.com/actions/cache), but use locally installed [cache-util](https://github.com/aurora-is-near/devops-stuff/tree/main/cache-util) instead.
~4m -> ~1m

Add build-caching to testing workflow

---

src/test_utils/mod.rs
src/tests/erc20.rs
src/tests/sanity.rs

@mfornet introduced a `Signer` struct a while back so that we don't have to keep track of nonces manually in our tests. In this PR we back port it to tests that were written before `Signer` was introduced. This makes the tests cleaner and easier to read, and reduces the total number of lines of code.

Refactor(tests): Use Signer

---

Cargo.toml

Context: @joshuajbouw asked if we should set the `opt-level` in the `dev` profile to match `release`, for consistency. I didn't see the harm, so gave it a shot, and it turns out this is not possible because of a complex interaction between wasmer's handling of panics and the rust compiler.
This is not a big deal because the wasm binaries we use in tests are still compiled with `--release`; it is only the test code that consumes and runs the wasm which will not be optimized, and that does not matter because performance of test execution is not particularly important.
As a result of this issue, I learned from @matklad that we need to enable `lto` on the `bench` profile in order to actually get link time optimization when running tests with `--release` (because compiling with `test` and …

Add options to bench profile

---

src/tests/standard_precompiles.rs

This test is being removed because it is line-for-line identical to the one above it and therefore does not add any value.
Based on its name, it seems the intention is that it was going to test we properly create promises (and do not create them in the case of revert). This functionality is tested in `src/tests/call_contract.rs` (not the most descriptive name), so it is safe to delete this duplicate test.

Remove duplicate test

---

src/sdk.rs

This was caught during the IOSG hackathon. It's something we probably would have caught ourselves if we had better compatibility test coverage, e.g. #170

Timestamp should be in milliseconds for Ethereum compatibility

---

.gitignore
src/engine.rs
src/test_utils/solidity.rs
src/test_utils/standard_precompiles.rs
src/tests/res/blockhash.sol
src/tests/sanity.rs

This PR defines an Aurora block hash for each height of the NEAR blockchain (including skipped ones). This definition is unique on different networks (via chain_id) and different accounts on the same network(*). It also includes a prefix byte which may allow us to change this scheme in the future and verify the change is implemented based on the hash output.
(*) Note: in the future, when we have sharding, this may need to change because there could be multiple Aurora accounts on the same network that are contributing to the same set of blocks.

feat(engine): Blockhash definition

---

src/transaction/mod.rs

Something I forgot to update after the Berlin support changes to upstream.
See https://eips.ethereum.org/EIPS/eip-2930 for spec.

Feat(Engine): Include cost of access list in intrinsic gas

---

src/engine.rs
src/lib.rs
src/tests/erc20.rs
src/tests/sanity.rs
src/transaction/mod.rs
src/types.rs

Someday we will require gas prices to be non-zero in order to cover the cost of running transactions on NEAR. This PR adds functionality to charge the transaction signer's address according to the gas limit and price, then pay the relayer's address based on the used gas, refunding the rest to the transaction signer.
Note: it is intentional that this only impacts the `submit` function because `call` is near-native in the sense that the NEAR transaction must have been signed by an access key for the corresponding account, therefore the caller is covering their own NEAR costs.

Feat(engine): Relayer payment

---

.github/workflows/scheduled_lints.yml

When we stopped installing the toolchain as part of the Action, we accidentally stopped running `clippy` with nightly in the scheduled lint. The whole point of this lint is to occasionally check if there are any new errors in our codebase with later versions of clippy.

Fix(CI): Scheduled lint is supposed to run nightly clippy

---

src/engine.rs
src/lib.rs
src/parameters.rs
src/test_utils/exit_precompile.rs
src/test_utils/mod.rs
src/test_utils/self_destruct.rs
src/tests/erc20.rs
src/tests/erc20_connector.rs
src/tests/sanity.rs
src/tests/standard_precompiles.rs
src/tests/state_migration.rs
src/types.rs

In response to the issue https://github.com/aurora-is-near/aurora-engine/issues/216 that @birchmd had found, it is true that certain errors should still be considered "successful" even though the execution had in fact failed. This fixes that.
Unfortunately, this is a breaking pub API change, but functionally similar.
DO note that this is missing an [important test](https://github.com/birchmd/aurora-engine/blob/state-revert-bug/src/tests/state_migration.rs#L34) which @birchmd had created as I am unsure if this test is actually correct, but I am currently unsure how such a test could be created.
Closes https://github.com/aurora-is-near/aurora-engine/issues/216.

Return actual status of a transaction

---

src/lib.rs
src/tests/sanity.rs

Now that https://github.com/aurora-is-near/aurora-engine/pull/218 is merged we can properly handle the case where the signer of a transaction does not have enough balance to cover the gas cost. Note in the original logic that the `sdk_unwrap()` caused a panic which meant the nonce increase was reverted (same problem as reported in https://github.com/aurora-is-near/aurora-engine/issues/216 ). This PR includes a `near-sdk-sim` test which shows the behaviour is now correct (this new test would have failed previously).

Fix(engine): do not panic when user has insufficient balance to cover gas

---

Cargo.lock
etc/state-migration-test/Cargo.lock

`make check` was not working after #221 because `git2` needs to also be updated.

Fix: Update lock files

---

src/connector.rs
src/lib.rs
src/precompiles/mod.rs
src/precompiles/native.rs
src/tests/sanity.rs

**Background:**
Previously we minted and burned bridged ETH in the NEP-141 contract when it became usable in the EVM. However, in #133 we changed that design to instead hold all the ETH currently available in the EVM in the Aurora account on the NEP-141 contract. This change was made because it makes the `ExitToNear` logic much simpler (it is simply a transfer from the Aurora account to the destination account in the NEP-141 contract).
However we did not mint tokens to cover the ones that were burned when they entered the EVM prior to #133. This includes the over 12k ETH that is held by the faucet.
**Issue:**
As a result, the `ExitToNear` functionality is now broken on testnet because the Aurora account in the NEP-141 contract has run out of tokens. Note: this only impacts testnet because …

Fix(testnet): Method to fix balance of aurora account

---

src/precompiles/hash.rs
src/precompiles/secp256k1.rs
src/sdk.rs

NEAR Protocol version 46 is now [live on mainnet](https://explorer.near.org/stats) so we can remove the testnet restriction on `ecrecover` and `ripemd` host functions.

Use math api host functions on mainnet

---

.github/workflows/builds.yml
.github/workflows/lints.yml
.github/workflows/scheduled_lints.yml
.github/workflows/tests.yml

Runners are finally isolated, so I don't expect problems with sccache anymore.
This commit does:
- Update `cache-util` usage. We need to cache more [things](https://github.com/aurora-is-near/devops-stuff/blob/main/runners/actions-runner/injected/configs/cache-util.json#L3), since runners don't share anything anymore with each other.
- Get rid of manual adding cargo binaries to `$HOME`

Adapt workflows to dockerized runners

---

src/engine.rs
src/tests/res/blockhash.sol
src/tests/sanity.rs

The reason for this change is to enable future micro-optimizations. We could cache the sha256 state which has all the static data already included in the hasher, then each hash computation only require pushing the block height and finalizing (rather than always needing to update the sha256 state with all the static data each time).

Fix(blockhash): Move block height to the end of hashing data

---

.github/workflows/tests.yml

#233 Changed a solidity contract, but the test failed in CI because it did not get recompiled (the compilation step does not happen when the artifact already exists). This ensures solidity artifacts are always recompiled.
An optimization to this would be to check if a `.sol` file was actually changed in the diff and only recompile if there is one.

Fix(CI): Ensure solidity artifacts are always recompiled

---

.github/workflows/lints.yml
.github/workflows/tests.yml
Cargo.lock
etc/state-migration-test/Cargo.lock

1.6.0 fixes

---

src/connector.rs
src/lib.rs
src/precompiles/mod.rs
src/precompiles/native.rs
src/tests/sanity.rs

The `balance_evm_and_nep_141` was called successfully in [this transaction](https://explorer.testnet.near.org/transactions/6o3y937tvCUCD5fVuEFcUU49L6oE3cMXtFp3xCWxGkKB). You can see the balances are now restored from the following CLI output:
```
$ ./bin/near view aurora ft_total_eth_supply_on_aurora
View call: aurora.ft_total_eth_supply_on_aurora()
Log [aurora]: Total ETH supply on Aurora: 12752741701607000064610
1.2752741701607e+22
$ ./bin/near view aurora ft_balance_of '{"account_id" : "aurora"}'
View call: aurora.ft_balance_of({"account_id" : "aurora"})
Log [aurora]: Balance of nETH [aurora]: 12424204949453000064603
1.2424204949453e+22
$ ./lib/aurora.js --network testnet get-balance 0xe9217bc70b7ed1f598ddd3199e80b093fa71124f
55857632000000000007
$ ./lib/aurora.js --network testnet …
```

Revert #225

---

.github/workflows/tests.yml
Cargo.lock
Cargo.toml
src/test_utils/mod.rs

As per the CI issues we are having, it is suspected that this may be the cause. So in response, this drops lazy static and instead uses a different kind of conditional compilation.

Drop lazy static in test-utils

---

src/connector.rs
src/tests/eth_connector.rs

There was a bit of confusion with the return required for `ft_balance_of`. It was initially interpreted that it needed simply to return the value as a string, but in fact, it needed to be returned surrounded by quotations.

Fix return format of `ft_balance_of`

---

CHANGES.md
src/lib.rs

This fixes an issue where the public `view` call was returning the result by name, but not the actual Borsh serialization. This fixes that.
**BREAKING**
Unfortunately, this breaks public API but for the better. The status return must be serialised to the equivalent of:
```rust
pub enum TransactionStatus {
Succeed(Vec<u8>),
Revert(Vec<u8>),
OutOfGas,
OutOfFund,
OutOfOffset,
CallTooDeep,
}
```
In a follow-up PR, a tests ensuring that we are not breaking API must be made.

Return view of transaction result as borsh

---

Makefile

[One previous PR](https://github.com/aurora-is-near/aurora-engine/pull/193), unfortunately, broke `evm_bully` feature enabling.
This PR fixes this feature and also suggests some reorganization to Makefile to make it more readable.

Fix evm_bully feature enabling in Makefile

---

Cargo.lock
Cargo.toml
src/benches/eth_deploy_code.rs
src/benches/eth_erc20.rs
src/benches/eth_standard_precompiles.rs
src/benches/eth_transfer.rs
src/test_utils/mod.rs
src/test_utils/self_destruct.rs
src/test_utils/solidity.rs
src/tests/erc20.rs
src/tests/erc20_connector.rs
src/tests/eth_connector.rs
src/tests/meta_parsing.rs
src/tests/sanity.rs
src/tests/state_migration.rs

There is an ongoing effort in the nearcore team to improve the runtime performance and this will ultimately lead to lower gas parameters; allowing us to fit more Ethereum gas per NEAR gas. In particular, preliminary results based on changes in https://github.com/near/nearcore/pull/4688 indicate that PR could increase the maximum Ethereum gas we can fit in one NEAR transaction by 7x.
In anticipation of that PR being merged in nearcore, we are upgrading our dependencies on nearcore to the latest commit. This will allow us to easily pull in new runtime changes to our benchmarks and thus measure their improvement.

Chore: Upgrade nearcore dependencies to latest commit

---

src/connector.rs
src/engine.rs
src/lib.rs
src/test_utils/mod.rs
src/tests/contract_call.rs
src/tests/erc20_connector.rs
src/tests/sanity.rs

While going through the nep-141 contract failure, it was discovered that while code itself was fine in the Engine, there was a requirement in the ERC-20 deploy contract for a `mint` method to only be called by an admin. Through continual improvements to the engine, we worked on removing this requirement to improve the user experience.
This reverts some changes from https://github.com/aurora-is-near/aurora-engine/pull/184 while we work on a script to change this data for all previously deployed ERC-20 contracts.

Fix issue with admin only contract call

---

src/benches/eth_deploy_code.rs
src/test_utils/mod.rs
src/tests/sanity.rs

The original benchmark did not attempt to make the code to deploy a valid EVM program. For some reason this still returned successfully and burned lots of gas, so I didn't think anything of it. However, my recent work with the 1inch contract showed that deploying a real contract was possible even if it consumed a lot of EVM gas. In this PR I make the deploy transactions used in the benchmark more realistic (actually writing some bytes into the code field of the created account).
As a result of this change we can establish a more accurate number for the EVM gas limit we can support within the 200 Tgas limit on NEAR. Based on fitting a line to the data point from this new benchmark (see plot below), I conclude we can support deploy transactions which consume more than 20 million EVM gas. …

Fix(deploy benchmark): Realistic deploy transaction

---

engine-sdk/src/lib.rs
engine-tests/src/tests/one_inch.rs
engine-tests/src/tests/res/timestamp.sol
engine-tests/src/tests/sanity.rs

The timestamp is supposed to be in seconds per the [Solidity docs](https://docs.soliditylang.org/en/latest/units-and-global-variables.html?highlight=block#block-and-transaction-properties).
Thanks @0x3bfc for reporting this!

Fix block.timestamp

---

Cargo.lock
engine-precompiles/src/lib.rs
engine-precompiles/src/native.rs
engine-tests/Cargo.toml
engine-tests/src/test_utils/exit_precompile.rs
engine-tests/src/tests/contract_call.rs
engine/src/engine.rs
etc/eth-contracts/contracts/test/Tester.sol

Closes #245 (see that ticket for details)
@paouvrard mentioned that an explicit event for ERC-20 exit, was not required, but it seemed easy to me to include it now, so I did.
This PR includes new tests showing the events are created.

Feat(exit precompile): Events for exit precompile calls.

---

.github/workflows/tests.yml

It turns out that consecutive runs of this tests in a single environment (and therefore in a single job) takes almost the same time as if doing this in parallel (2 minutes). This is probably because of reusing build artifacts.
Meanwhile, reducing number of parallel jobs decreases CPU usage on our CI-machine

Merge all nets test-suites into single CI job

---

engine/src/lib.rs

It will be useful to know the public key of the signer when creating a submit. This change prevents us from having to do this process manually which can be extremely taxing and simply non-trivial.
We already require the sender's details when checking the nonce, this simply just emits a log of that retrieved sender.

Add logging of public key of the signer

---

engine-precompiles/src/hash.rs

This fixes the ripemd160 gas cost which incorrectly is charging 10x less than it should be right now.
Do note that @mrLSD is working on tests for precompiles using ETH tests.
Closes #302.

Fix ripemd160 word cost

---

engine-tests/src/tests/sanity.rs

The purpose of this test is to make sure that if we accidentally change the binary format of the `EngineState` then we will know about it. This is important because changing the state format will break the contract unless we do a state migration.

Test asserting we do not change the engine state binary format

---

engine-tests/src/tests/eth_connector.rs
engine-tests/src/tests/sanity.rs
engine-types/src/types.rs
engine/src/connector.rs
engine/src/deposit_event.rs
engine/src/lib.rs

There was an incident detailed in #335. This fixes that incident.
In the future, it would be a good idea to make the test framework more general which would allow for different sizes of inputs to the Engine.
This is labelled as critical as we have to rescue two users funds in a timely manner.
This closes #335.

Fix 0x prefix on address, if there

---

Cargo.lock
engine-precompiles/src/lib.rs
engine-tests/src/benches/nft_pagination.rs
engine-tests/src/test_utils/erc20.rs
engine-tests/src/test_utils/exit_precompile.rs
engine-tests/src/test_utils/mod.rs
engine-tests/src/test_utils/one_inch/liquidity_protocol.rs
engine-tests/src/test_utils/self_destruct.rs
engine-tests/src/test_utils/solidity.rs
engine-tests/src/test_utils/standard_precompiles.rs
engine-tests/src/test_utils/uniswap.rs
engine-tests/src/tests/access_lists.rs
engine-tests/src/tests/eip1559.rs
engine-tests/src/tests/erc20.rs
engine-tests/src/tests/erc20_connector.rs
engine-tests/src/tests/mod.rs
engine-tests/src/tests/one_inch.rs
engine-tests/src/tests/sanity.rs
engine-tests/src/tests/uniswap.rs
engine-types/src/types.rs
engine/src/engine.rs
engine/src/lib.rs
engine/src/transaction/eip_1559.rs
engine/src/transaction/eip_2930.rs
engine/src/transaction/legacy.rs
engine/src/transaction/mod.rs
etc/state-migration-test/Cargo.lock

Adds initial [EIP-1559](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1559.md) support for the London hardfork.
There has been numerous changes done in this PR. Notably, I made a geth-like `NormalizedEthTransaction` which given the current fork will use that structure. This is important as for the first time instead of adding fields, 1 was taken away, and 2 additional were added so it led to a bit of a large redesign.

Add initial EIP-1559 support

---

engine-tests/src/test_utils/solidity.rs
engine-tests/src/tests/res/caller.sol
engine-tests/src/tests/sanity.rs

Adds a test showing the correct address is returned by the engine.
This means the issue reported in #336 must not come from the engine, and instead must arise from elsewhere (maybe the relayer?).
Closes #336

Test verifying the EVM log returns the correct address

---

engine-precompiles/src/blake2.rs
engine-precompiles/src/bn128.rs
engine-precompiles/src/hash.rs
engine-precompiles/src/identity.rs
engine-precompiles/src/lib.rs
engine-precompiles/src/modexp.rs
engine-precompiles/src/native.rs
engine-precompiles/src/secp256k1.rs
engine-tests/src/tests/erc20.rs
engine/src/engine.rs

This refactors the precompiles to take a `self` parameter as part of `run`. This means the objects implementing the precompiles can hold some state. In particular, the exit precompiles can hold the `current_account_id` instead of needing to look it up via `sdk::current_account_id()`. This is useful because it means the precompiles will not need to receive any `Env` object once we factor out blockchain context related lookups into a trait (as part of the standalone engine project).

Remove sdk::current_account_id usage from engine-precompiles

---

engine-tests/src/test_utils/mod.rs
engine/src/connector.rs
engine/src/engine.rs
engine/src/fungible_token.rs
engine/src/lib.rs
engine/src/map.rs

The primary goal of this PR is to remove the `Default` trait bound that was required on the `IO` type after #314 . The primary reason for this trait bound was the usage of `Default` in `LookupMap` and `BijectionMap`. As a result, this PR removes `LookupMap` and refactors `BijectionMap` to no longer have a `Default` implementation, as well as to be more type-safe.
This is change does not impact the runtime behaviour of the engine in any way. It is continuing the path towards being able to run the engine without the NEAR runtime (ie as a standalone binary).

Remove Default trait bound from engine IO

---

engine/src/admin_controlled.rs
engine/src/connector.rs
engine/src/engine.rs
engine/src/fungible_token.rs
engine/src/lib.rs

The purpose of this PR is to move as much sdk usage related to blockchain environment (e.g. `current_account_id`, `predecessor_account_id`) from core logic, pushing it to `lib` (which is the boundary of our application). This will make it much easier to factor out blockchain context related lookups into a trait (as part of the standalone engine project).
Note: this PR is built on top of #342 and #346 those should be reviewed and merged first. To see only the new changes from this PR only look at the diff from the last commit.

Remove some sdk usage from core logic

---

engine-sdk/src/lib.rs
engine-sdk/src/near_runtime.rs
engine-sdk/src/promise.rs
engine-types/src/parameters.rs
engine/src/connector.rs
engine/src/engine.rs
engine/src/fungible_token.rs
engine/src/lib.rs

Another step towards removing dependency on NEAR host functions from the engine (allowing it to compile as a standalone binary).
The main changes here are:
1. Connector and FungibleToken never schedule promises, they always return data representing the promise. This data is used to actually schedule the promise at the end of the transaction in `lib.rs`. The reason for this change is to prevent pushing a `PromiseHandler` all the way down into those modules.
2. The engine now needs a `PomiseHandler` to execute EVM transactions. This is because the exit precompiles cause NEAR promises to be scheduled.
3. `storage_unregister` (part of the storage management standard) was not previously exposed as a public method, now it is (and it follows the same patterns as other methods in terms of passing …

Factor out NEAR promise host functions into a trait (#353)

---

engine-tests/src/test_utils/self_destruct.rs
engine-tests/src/tests/erc20_connector.rs
engine-types/src/types.rs
engine/src/engine.rs
engine/src/lib.rs
engine/src/parameters.rs

**Implementation to address [issue of attaching ETH balance to the transation](https://github.com/aurora-is-near/aurora-engine/issues/309)**
PR fixes #309
**Implementation for deserialized values from bytes to current or legacy Borsh-encoded parameters for passing to the engine `call` function, and to provide backward type compatibility:**
- Handling in a generic way current and legacy Borsh-encoded parameters returned by the `io.read_input_borsh()` function call, with fallback to previous `FunctionCallArgsLegacy` data structure, to provide backward type compatibility.
- Type matching from `CallArgsType` into current and legacy Borsh-encoded parameters, for passing to the `call` function, and to provide backward type compatibility.
**Changes in this feature branch:**
- Preserve legacy …

Borsh deserialized value field for call args

---

engine-tests/src/tests/one_inch.rs
engine-types/src/types.rs
engine/src/admin_controlled.rs
engine/src/connector.rs
engine/src/deposit_event.rs
engine/src/engine.rs
engine/src/fungible_token.rs
engine/src/lib.rs
engine/src/parameters.rs

The purpose of this PR is to remove panic calls (`sdk_unwrap`, `assert`, etc) from the connector logic. The reasons for this are:
1. Continue to remove references to NEAR host functions from core logic. When we have removed all the host functions then we will be able to compile a standalone binary from the engine (as required for the standalone engine project).
2. Panics should only happen at the edge of applications (unless they are fatal errors) where there is no other way to handle the error. In smart contract development this principle is often ignored (or alternatively all errors are considered fatal) because panicking in a contract only fails the current transaction. However in the standalone engine a panic will bring down the whole process which will be a big problem for the …

Refactor(eth-connector): Use Result return values instead of panicking

---

Cargo.lock
engine-sdk/Cargo.toml
engine-sdk/src/lib.rs
engine-sdk/src/promise.rs
engine-sdk/src/types.rs
engine-tests/Cargo.toml
engine/Cargo.toml
engine/src/engine.rs
etc/state-migration-test/Cargo.lock
etc/state-migration-test/Cargo.toml

This is the final step in removing the NEAR host functions from core engine code. All host function access is now gated behind the contract feature flag and the `engine` crate compiles with and without this feature. The standalone engine will not use this feature, allowing it to compile as a standalone binary without any NEAR host functions.
Note: I did not implement any logging for the standalone case. This will need to be done in a future PR.
Note: This PR depends on #355 that one should be reviewed and merged first. To review this PR only look at the last commit.

Gate all NEAR host functions behind the contract feature

---

engine-precompiles/src/blake2.rs
engine-precompiles/src/bn128.rs
engine-precompiles/src/hash.rs
engine-precompiles/src/identity.rs
engine-precompiles/src/lib.rs
engine-precompiles/src/modexp.rs
engine-precompiles/src/native.rs
engine-precompiles/src/secp256k1.rs
engine-sdk/src/near_runtime.rs
engine-sdk/src/prelude.rs
engine-types/src/lib.rs
engine-types/src/types.rs
engine/src/connector.rs
engine/src/fungible_token.rs
engine/src/lib.rs

While working on the `engine-standalone`, I have come to realise that the gas usages, since they are costs, should be using newtypes and not a normal type. This prevents dev error in the case of trying to use the wrong values, in the wrong areas which can lead to unintentional bugs.
Newtypes are 0 cost, therefore this is a wise decision to add this bit of work in. There will be more work around these areas if the need arises as I continue work through out the library and notice improvements that should be done. This is one of them that I had noticed.
This is a semantic change and intended for dev experience and will help the code be at a higher level of quality. From this point forward, the types will be made aware to the developer when working on the library and forces them to be …

Chore: Newtypes for gas

---

Cargo.lock
Cargo.toml
Makefile
engine-precompiles/src/lib.rs
engine-sdk/Cargo.toml
engine-sdk/src/env.rs
engine-sdk/src/promise.rs
engine-standalone/Cargo.toml
engine-standalone/LICENSE
engine-standalone/src/ffi.rs
engine-standalone/src/main.rs
engine-standalone/src/tests/mocks/mod.rs
engine-standalone/src/tests/mocks/promise.rs
engine-standalone/src/tests/mocks/storage.rs
engine-standalone/src/tests/mod.rs
engine-standalone/src/tests/sanity.rs
engine-standalone/src/trace.rs
engine-types/src/parameters.rs
engine-types/src/types.rs

The purpose of this change is to add geth-like [`debug_traceTransaction`] logic to [Sputnik EVM] (rust-blockchain/evm). On top of that the ability to run a standalone engine that is able to keep in sync with the network EVM.
Why this is an important change is that it is absolutely necessary for this logic for both Block Scout and Etherscan's upcoming block explorer for Aurora.

Feat(standalone): Standalone

---

engine/src/engine.rs
engine/src/lib.rs
engine/src/transaction/mod.rs

Moves the `submit` logic so that we will be able to call it directly from the standalone engine (useful for debug trace).

Refactor(engine): Move submit logic into engine module

---

engine-tests/Cargo.toml
engine-tests/src/prelude.rs
engine-tests/src/tests/meta_parsing.rs

When running `check --all-targets --all-features`, a compilation error occurs:
```
error[E0432]: unresolved imports `crate::meta_parsing`, `crate::prelude::keccak`
--> engine-tests/src/tests/meta_parsing.rs:2:12
|
2 |     crate::meta_parsing::{near_erc712_domain, parse_meta_call, prepare_meta_call_args},
|            ^^^^^^^^^^^^
|            |
|            unresolved import
|            help: a similar path exists: `aurora_engine::meta_parsing`
3 |     crate::prelude::keccak,
|     ^^^^^^^^^^^^^^^^^^^^^^ no `keccak` in `prelude`
```
This simply fixes that issue so that the correct imports are being used.

Fix:  Meta parsing imports

---

engine-standalone-storage/src/lib.rs
engine-standalone-storage/src/sync/mod.rs
engine-standalone-storage/src/sync/types.rs
engine-tests/src/test_utils/standalone/mocks/mod.rs
engine-tests/src/tests/standalone/mod.rs
engine-tests/src/tests/standalone/sync.rs
engine-types/src/parameters.rs
engine/src/connector.rs
engine/src/deposit_event.rs
engine/src/engine.rs
engine/src/parameters.rs
engine/src/proof.rs
engine/src/transaction/eip_1559.rs
engine/src/transaction/eip_2930.rs
engine/src/transaction/legacy.rs
engine/src/transaction/mod.rs

Note: This PR is on top of #379 so that PR should be reviewed and merged first. To review the changes for this PR only look at the last commit.
This PR introduces a high level message format for passing new blockchain information into the standalone storage engine. This will allow it to stay in sync with the blockchain. Note this PR does not yet make use of these data structures; in a future PR they will be constructed based on messages received from the NATS message broker (which is still a work in progress from what I understand from @artob and @JonathanLogan ).
To help guide reviewers, the core logic is found in the `consume_message` function.

Feat(standalone): Structures and logic for keeping storage in sync with the blockchain

---

engine-standalone-tracing/src/sputnik.rs
engine-standalone-tracing/src/types.rs
engine-standalone/src/ffi.rs
engine-tests/src/tests/standalone/tracing.rs

~This is a follow up PR to #383 that one should be reviewed and merged first. To see only the changes from this PR look only at the last commit.~
The purpose of this PR is to produce a `TransactionTrace` from the events emitted by SputnikVM.
More comprehensive testing is needed to make sure this conversion is always done correctly, but a basic sanity test present in this PR does pass. It would be nice if we had more examples of geth traces to compare against, does anyone know if there is a way we can get them?
In the meantime, I suggest merging this PR as a baseline and we can make iterative corrections to edge cases as more testing is done.

Feat(standalone): Capture geth-like tracing from SputnikVM events

---

engine-sdk/src/env.rs
engine-sdk/src/near_runtime.rs
engine-standalone-storage/src/relayer_db/mod.rs
engine-standalone-storage/src/sync/mod.rs
engine-tests/src/test_utils/standalone/mocks/mod.rs
engine-tests/src/test_utils/standalone/mod.rs
engine-tests/src/tests/standalone/sanity.rs
engine-types/src/types.rs
engine/src/connector.rs
engine/src/fungible_token.rs
engine/src/lib.rs

PR related to the issue: #381
Increased NEAR Gas:
* `deposit` to 80 Tgas
* `ft_on_transfer` 30 TGas
The main solution is not to fix the amount of gas for promise call `ft_on_transfer`. For this, a formula is introduced according to which we can use more gas, depending on how much gas was initially released. 
`GAS_FOR_FT_ON_TRANSFER = prepaid_gas - GAS_FOR_FT_TRANSFER_CALL - GAS_FOR_RESOLVE_TRASNFER`
* added new Sdk and Env method - `prepaid_gas`
* introduced a new constant `GAS_FOR_FT_TRANSFER_CALL = 35 TGas`. This constant indicates how much gas is allocated to make a call `ft_transfer_call`.
* To invoke a ft_on_transfer` promise, a formula for gas counting has been introduced: `GAS_FOR_FT_ON_TRANSFER = prepaid_gas - GAS_FOR_FT_TRANSFER_CALL - GAS_FOR_RESOLVE_TRASNFER`
This will allow …

Increase NEAR Gas for ft_on_transfer

---

engine-standalone-tracing/src/sputnik.rs
engine-standalone-tracing/src/types.rs
engine-tests/src/tests/standalone/tracing.rs

Geth traces include a `gas` value which counts down from the gas limit. In this PR we capture this information from the SputnikVM events and validate it is the same as the values in example traces from etherscan.

Feat(standalone): Add debug tracing of remaining gas values

---

Cargo.lock
engine-precompiles/Cargo.toml
engine-precompiles/src/lib.rs
engine-sdk/src/lib.rs
engine-tests/Cargo.toml
engine-types/src/lib.rs
engine-types/src/storage.rs
engine/Cargo.toml
engine/src/fungible_token.rs
engine/src/lib.rs
etc/state-migration-test/Cargo.lock

The following changes are made in order to engine on stable rust (only works with `std`):
- Pass `std` feature on to `rjson`
- Include `std` feature in `engine-precompiles` and pass it on to its deps
- Remove unnecessary unstable feature `array_methods`

Fix(dep): Pass std feature on to rjson library

---

engine-tests/src/test_utils/mod.rs
engine-tests/src/tests/erc20.rs
engine-tests/src/tests/one_inch.rs
engine-tests/src/tests/sanity.rs
engine-tests/src/tests/uniswap.rs

NEAR is reducing the wasm cost again: near/nearcore#5365
Revisited our gas usage regression tests with the new bounds.
Related to: #380

Feat(benchmarks): update gas bounds after wasm cost reduction

---

engine-tests/src/test_utils/mocked_external.rs
engine-tests/src/test_utils/mod.rs
engine-tests/src/tests/erc20.rs
engine-tests/src/tests/one_inch.rs
engine-tests/src/tests/sanity.rs
engine-tests/src/tests/uniswap.rs

From mainnet data we know the average trie depth for Aurora Engine IO operations is 10. In this PR we wrap the `MockedExt` struct to include this hardcoded trie touching value. This allows us to get more realistic estimates of gas costs from our local tests. Notably, with this change the gas costs of 1inch and uniswap transactions in our regression tests go up, and the fraction of cost due to wasm execution goes down. The new values are more in line with what we expect based on real mainnet transactions.

Feat(tests): Mock touching trie nodes

---

engine/src/lib.rs

This is not a big deal because we never use the `stage_upgrade` functionality. But it was pointed out to us that `deploy_upgrade` should also be `owner_only` for security reasons if we did ever use that upgrade path. This PR adds this restriction.

Fix: Only allow owner to call deploy_upgrade

---

Cargo.lock
engine-precompiles/Cargo.toml
engine-precompiles/src/lib.rs
engine-standalone-storage/Cargo.toml
engine-standalone-tracing/Cargo.toml
engine-tests/Cargo.toml
engine-tests/src/tests/res/reverter.sol
engine-tests/src/tests/sanity.rs
engine/Cargo.toml
engine/src/engine.rs
etc/state-migration-test/Cargo.lock

@0x3bfc pointed out that presently the Engine always returns the address the contract would be deployed at, regardless of if the deploy execution was successful or not. In this PR we ensure to pass the error message on in the case of failure.

Fix(engine): Return revert error message during contract deploy

---

Cargo.lock
engine-tests/Cargo.toml
engine-tests/src/tests/sanity.rs

On the nearcore's side, contract runtime team frequently makes
substantial changes to wasmer and wants to change those changes with
aurora. If aurora has a direct dependency to wasmer, we need to apply
more Cargo.toml patches to test this out.
Moreover, wasmer is not needed for this particular test -- we don't need
to compile WASM to machine code (which is what wasmer is doing), we just
need to run some analysis on wasmer. That's a much simpler thing to do
conceptually, and something `walrus` crate is typically used.

Avoid using wasmer directly

---

.gitattributes

No super-strong feelings here, I can work-around on my side! But yeah,
the current setup feels a bit odd to me, as it's quite unusual. 
git&github generally handle Cargo.lock reasonably nowdays by default.
Our current explicit setting prevent changes to Cargo.lock being visible
in some tools
(https://marketplace.visualstudio.com/items?itemName=kahole.magit in my
case),  which makes working on upgrading dependencies harder.
Changes to Cargo.lock are the most important ones, as one-line
Cargo.lock addition might bring in thousands of lines of new code. They
generally should be audited with above-average scrunity, not ignored.

use default git attributes for Cargo.lock

---

Cargo.lock
engine-precompiles/Cargo.toml
engine-precompiles/src/blake2.rs
engine/Cargo.toml
etc/state-migration-test/Cargo.lock

This pulls
https://github.com/near/near-blake2/commit/cebb7df79608a7058017940830d37c37d55d21fe
which just renames blake2. It's parent, 736ff60, is what we are using
currently. There are some extra commits on top of that in master, but I
decided not to pull them in just yet, to minimize change.
The primary motivation here is making it easy to upgrade other things:
blake2 = { git = "https://github.com/near/near-blake2.git", version = "0.9.1", default-features = false }
makes that tricky, as there's no longer `blake2` package at that URL!

switch to rebranded blake2

---

engine/src/json.rs

This now is very much used, so `allow` is confusing

remove unused unused

---

Cargo.lock

This pulls in https://github.com/near/wasmer/pull/106 which should allow
us to upgrade the nightly version we use. An alternative would be to
pull in https://github.com/aurora-is-near/rjson/pull/1, which should
(0.7 confidence) allow us to switch to stable.

chore: make aurora compatible with modern nightlies

---

engine-tests/src/test_utils/solidity.rs
engine-tests/src/tests/res/bench.sol
engine-tests/src/tests/sanity.rs

Reproduces in Solidity the [contract used by the nearcore contract runtime](https://github.com/near/nearcore/blob/83fc0f7d6b212bacc49f058e7400743de3e59783/runtime/runtime-params-estimator/test-contract/src/lib.rs#L1031-L1043) team to benchmark wasm. This fulfils a request from @matklad to have such a contract.

Benchmark contract performing only pure arithmetic and memory operations

---

engine-tests/src/tests/erc20_connector.rs
engine/src/engine.rs

I don't think anyone has ever submitted any transaction to Aurora without a `chain_id`, so this should not break anything, and it should close potential shenanigans  since we do not expect any legitimate user to not provide a `chain_id`.

Fix(engine): Require chain_id

---

engine/src/engine.rs

By making use of `&&` laziness, we save some IO operations, which adds
up to 4% for the uniswap test_uniswap_input_multihop.

optimize is_account_empty

---

Cargo.lock
engine-precompiles/Cargo.toml
engine-standalone-storage/Cargo.toml
engine-standalone-tracing/Cargo.toml
engine-standalone-tracing/src/sputnik.rs
engine-standalone-tracing/src/types.rs
engine-tests/Cargo.toml
engine-tests/src/tests/one_inch.rs
engine-tests/src/tests/sanity.rs
engine-tests/src/tests/uniswap.rs
engine-transactions/Cargo.toml
engine/Cargo.toml
etc/state-migration-test/Cargo.lock

Upgrading to latest SputnikVM includes optimizations which make our contract use 15%-20% less NEAR gas.

Fix(engine): Upgrade to latest SputnikVM

---

engine-sdk/src/dup_cache.rs
engine-sdk/src/lib.rs
engine-tests/src/tests/one_inch.rs
engine-tests/src/tests/sanity.rs
engine-tests/src/tests/uniswap.rs
engine/src/engine.rs

This is an interim change in response to #443 . Of course a better approach is to review the SputnikVM code to stop it from making the duplicate reads in the first place, but this simple caching solution saves us 10%-15% of our gas usage right now, so it seems worth getting in immediately. We can always revert this after SputnikVM has been properly fixed.

Fix(engine): Simple cache to stop consecutive duplicate reads

---

Cargo.lock
engine-precompiles/Cargo.toml
engine-standalone-storage/Cargo.toml
engine-standalone-tracing/Cargo.toml
engine-standalone-tracing/src/sputnik.rs
engine-tests/Cargo.toml
engine-tests/src/tests/one_inch.rs
engine-tests/src/tests/sanity.rs
engine-tests/src/tests/uniswap.rs
engine-transactions/Cargo.toml
engine/Cargo.toml
etc/state-migration-test/Cargo.lock

Pulls in the latest SputnikVM optimizations including:
- https://github.com/aurora-is-near/sputnikvm/pull/10
- https://github.com/aurora-is-near/sputnikvm/pull/5
The wasm gas usage decreases by around 30% with these optimizations (as illustrated in the pure arithmetic benchmark), but since our costs are still largely IO bound this translates into pretty small gains for real contracts (other benchmarks decrease by 1-2 Tgas). However, this is still important to release since it is known to fix at least one example of a failed transaction (see https://github.com/aurora-is-near/aurora-engine/pull/454 ).

Engine: Upgrade to latest SputnikVM changes

---

engine-tests/src/tests/uniswap.rs
engine/src/engine.rs

Adding the another size-1 LRU cache for EVM contract code is helpful in reducing duplicate reads because it appears to be a pattern in contracts compiled by solidity to use the `EXTCODESIZE` opcode before calling an address (both operations require reading the target address's code).
Additionally, we can use the caches we have already added in the `Backend::exists` implementation for the Engine. This prevents some duplicate reads where SputnikVM ends up checking if an address is empty twice because it does not assume `Backend::exists` will return false for empty accounts (our implementation does have the property that `exists` returns false if and only if the account is empty, so the second check is redundant for us, but I don't want to make a breaking change to the core assumptions of …

Engine: further caching optimizations

---

engine-standalone-storage/src/relayer_db/mod.rs
engine-standalone-storage/src/sync/mod.rs
engine-transactions/src/lib.rs

It doesn't make sense that turning `EthTransactionKind` into `Vec<u8>` consumes the object when the implementation only requires a reference. Changing the definition to `From<&EthTransactionKind>` keeps the implementation the same and allows more flexibility for users of the `aurora-engine-transactions` library.

Use EthTransactionKind reference to serialize into bytes

---

engine-tests/src/tests/sanity.rs
engine-transactions/src/backwards_compatibility.rs
engine-transactions/src/legacy.rs
engine-transactions/src/lib.rs
engine/src/engine.rs

Fixes the issue raised in https://github.com/aurora-is-near/aurora-relayer/issues/197
Essentially, if the Engine treats transactions to the zero address the same as transactions with an empty `to` field, then two incorrect things happen
1. Transactions to the zero address create a new contract (this does not happen on Ethereum)
2. The Engine does not correctly derive the sender of transactions to the zero address, causing incorrect state changes and mismatch with the explorer.
This PR fixes these problems by letting the zero address be a possible value of the `to` field.

Fix(Engine): Transactions to the zero address are not the same as transactions with empty to field

---

engine-precompiles/src/account_ids.rs
engine-precompiles/src/lib.rs
engine-tests/src/tests/account_id_precompiles.rs
engine-tests/src/tests/mod.rs
engine-tests/src/tests/res/AccountIds.sol
engine/src/engine.rs

Related to https://github.com/aurora-is-near/aurora-engine/discussions/461
This PR provides custom precompiles to access the `predecessor_account_id` and `current_account_id` NEAR host functions from the Aurora EVM. See the discussion above for the motivation of adding these.

Feat(Engine): Precompiles for predecessor_account_id and current_account_id

---

engine-precompiles/src/lib.rs
engine-sdk/src/lib.rs
engine/src/lib.rs

1. This feature is only needed in the engine itself (the only crate with a wasm target).
2. We only need this feature when compiling to wasm.
Fixing this will allow enabling the logging feature in the standalone engine (though it still needs a real implementation for this to do anything)

Fix features related to panic_info_message

---

engine-standalone-storage/src/sync/mod.rs

Fixes a bug in the standalone engine that was making it process `deposit` (i.e. bridging transactions) incorrectly.

Fix(standalone): set predecessor_account_id appropriately when executing promise callbacks

---

engine-precompiles/src/lib.rs
engine-precompiles/src/native.rs
engine/src/engine.rs
engine/src/lib.rs

To fully verify the standalone engine processes transactions exactly the same as what is deployed on chain, including `SubmitResult` return values, the standalone must be able to run the exit precompiles because they create EVM logs (and therefore have an observable effect on the `SubmitResult`).

Fix(precompiles): Allow exit precompiles to work in the standalone engine

---

engine-precompiles/src/native.rs
engine-standalone-storage/src/diff.rs
engine-standalone-storage/src/lib.rs
engine-standalone-storage/src/sync/mod.rs
engine-standalone-storage/src/sync/types.rs
engine-tests/src/test_utils/mod.rs
engine-tests/src/test_utils/standalone/mod.rs
engine-tests/src/tests/standalone/json_snapshot.rs
engine-tests/src/tests/standalone/storage.rs
engine-tests/src/tests/standalone/sync.rs
engine-types/src/parameters.rs
engine/src/connector.rs
engine/src/engine.rs
engine/src/fungible_token.rs
engine/src/lib.rs
engine/src/parameters.rs

This PR makes several improvements to the standalone engine:
1. An Aurora "Transaction" is correlated with a NEAR receipt instead of a NEAR transaction. This is important because on NEAR the receipt is the atomic unit, and there are some operations on Aurora which span multiple receipts.
2. Ensure the standalone can handle all Engine contract methods which mutate state
3. Add a function to revert the effects of a transaction, this is needed if we detect a discrepancy in the wasm and standalone implementations and need to prevent the state from diverging from the version on-chain.
4. Add a function for taking a snapshot of the state (this is useful in debugging), and a test for it
5. Add a function for finding all the transactions which changed the value of a given Engine key (this is …

Standalone engine improvements

---

engine-precompiles/src/account_ids.rs
engine-precompiles/src/lib.rs
engine-sdk/src/near_runtime.rs
engine-tests/src/test_utils/mod.rs
engine-tests/src/tests/account_id_precompiles.rs
engine/src/engine.rs
engine/src/lib.rs

This PR addresses the issue of the `predecessor_account_id` precompile failing in view calls. It does this by creating a new instance of the `Env` trait where it inserts default values for the methods that are not defined in NEAR during view calls. This instance of `Env` is used in the Engine's `view` method. To verify this fix works, our tests are also updated to put the NEAR runtime in view-call mode when executing a read-only call. As additional insurance, the call to `Env::predecessor_account_id` is made lazy; instead of calling the method when constructing the `Precompiles` struct, instead the `Env` reference itself is passed to the precompile, so that only when the `predecessor_account_id` precompile is invoked does that method get called. This means if someone accidentally calls …

Fix(Engine): Predecessor id precompile works in view calls

---

engine-precompiles/src/account_ids.rs
engine-precompiles/src/lib.rs
engine-precompiles/src/native.rs
engine-precompiles/src/prepaid_gas.rs
engine-precompiles/src/random.rs
engine-tests/src/tests/mod.rs
engine-tests/src/tests/prepaid_gas_precompile.rs

Adds another custom precompile for Aurora. This one exposes the `prepaid_gas` NEAR host function. It may be useful for Aurora-based cross contract calls in the future.

Feat(Engine): Add custom precompile for NEAR prepaid_gas

---

engine-standalone-storage/src/lib.rs
engine-tests/src/tests/standalone/storage.rs

These functions might be useful in satisfying the non-numeric [Ethereum JSON RPC block parameter](https://eth.wiki/json-rpc/API#the-default-block-parameter) values.

Feat(standalone): Function to get latest/earliest block

---

Cargo.lock
engine-precompiles/Cargo.toml
engine-precompiles/src/blake2.rs
engine/Cargo.toml
etc/state-migration-test/Cargo.lock

Issue related to `blake2_f` function compatibility.
Related to:
* [EIP-152](https://eips.ethereum.org/EIPS/eip-152)
* [Blake2 RFC-7693](https://datatracker.ietf.org/doc/html/rfc7693#section-3.2)
Realted to *EIP-152* `compress` function should accept parameters: `h, m, t, f`

Fix near-blake2 dependency

---

engine-tests/src/tests/repro.rs

I'll be adding more tests reproducing gas errors to our tests. This change simply factors out code that will be common to all the tests to make it easier to add the new ones.

Refactor repro tests to have less boilerplate

---

Cargo.lock
engine-standalone-storage/src/sync/mod.rs
engine-standalone-tracing/Cargo.toml
engine-standalone-tracing/src/types.rs
engine-types/src/types/gas.rs

This is required for borealis-engine as the base branch.
It was really unfortunate that OpCode didn't provide serde, even if it is just a single `u8`. I implemented custom de/serialization methods. If you have any simpler way, let me know.

Add serde for TraceTransaction

---

engine-standalone-storage/src/sync/mod.rs
engine-tests/src/test_utils/standalone/mod.rs
engine-tests/src/tests/standalone/storage.rs
engine-tests/src/tests/standalone/sync.rs
engine-tests/src/tests/standalone/tracing.rs

This fixes an issue in the standalone engine where it would not return the full `TransactionIncludedOutcome` object on very old testnet blocks due to the current engine code not being able to read the old storage layout (before we introduced the version prefix). With this change the error will be included in the `TransactionIncludedOutcome` response so that the caller can handle the error in the same way they would handle any other `SubmitResult` error.

Fix(standalone): include possible execution errors in the TransactionIncludedOutcome 

---

engine-standalone-storage/src/sync/mod.rs
engine-tests/src/test_utils/standalone/mocks/mod.rs
engine/src/connector.rs
engine/src/engine.rs
engine/src/lib.rs

This prevents an issue in the standalone engine where it can crash on old testnet blocks where the storage layout is different from the current code.

Fix(connector): Return an error when storage cannot be read instead of panicking

---

engine-standalone-storage/Cargo.toml
engine-tests/Cargo.toml

This allows dependent libraries to turn on/off any of the rocksdb compression features.

Standalone: forward underlying rocksdb crate features

---

engine-standalone-storage/src/error.rs
engine-standalone-storage/src/lib.rs
engine-standalone-storage/src/sync/mod.rs
engine-tests/src/test_utils/standalone/mod.rs
engine-tests/src/tests/repro.rs
engine-tests/src/tests/standalone/json_snapshot.rs

The standalone engine must not assume the account ID of the account executing the transactions is `aurora` so that it can be used with other deployments of the engine on-chain.
There are multiple ways to accomplish this, so here is some rational behind my chosen solution of storing the account ID in the DB directly.
1. The standalone engine DB only holds state for a single engine instance. This could be changed, but this adds additional complexity without adding much value in my opinion. I think it is unlikely that any on-chain instances of the engine will have so little traffic that all of the queries about them could be served by a single standalone instance. If each on-chain instance requires at least one standalone instance off-chain, then there is no reason to be able to have …

Fix(standalone): Do not assume "aurora" account ID

---

engine-precompiles/src/secp256k1.rs

If the 'v' byte is incorrect, the ecrecover precompile must return an empty slice.
Reference: https://github.com/ethereum/go-ethereum/blob/440c9fcf75d9d5383b72646a65d5e21fa7ab6a26/core/vm/contracts.go#L180
Task https://app.clickup.com/t/2c7n5mg

Fix secp256k1 handling of an incorrect V byte

---

engine-tests/src/tests/erc20_connector.rs
engine/src/engine.rs

Reverts: #432.
At the time, given future infrastructure direction and the fact that nobody had used legacy transactions, it had made sense to require a chain ID. However given issue #519, there are other EIPs [which do in fact require legacy transactions](https://eips.ethereum.org/EIPS/eip-1820).
This reverts the Chain ID requirement and unblocks the user at the described issue.

Fix(engine): revert Chain ID requirement

---

Cargo.lock
engine-precompiles/Cargo.toml
engine-precompiles/src/blake2.rs

This is a better improvement since we only need the compression algorithm from [RFC 7693](https://datatracker.ietf.org/doc/html/rfc7693). 
This way it's more portable and easily maintained. It is tested with our usual blake2 tests. In theory, we may see some slight gas reduction and certainly binary reduction. We also don't need to maintain another library as this specific algorithm is straightforward.

Chore(precompile): Include blake2 compression directly

---

Cargo.lock
Cargo.toml
engine-precompiles/Cargo.toml
engine-precompiles/src/secp256k1.rs
engine-tests/Cargo.toml
engine-tests/src/benches/eth_deploy_code.rs
engine-tests/src/benches/eth_erc20.rs
engine-tests/src/benches/eth_standard_precompiles.rs
engine-tests/src/benches/eth_transfer.rs
engine-tests/src/benches/nft_pagination.rs
engine-tests/src/test_utils/mod.rs
engine-tests/src/test_utils/standalone/mod.rs
engine-tests/src/tests/access_lists.rs
engine-tests/src/tests/eip1559.rs
engine-tests/src/tests/erc20.rs
engine-tests/src/tests/erc20_connector.rs
engine-tests/src/tests/multisender.rs
engine-tests/src/tests/one_inch.rs
engine-tests/src/tests/sanity.rs
engine-tests/src/tests/standalone/json_snapshot.rs
engine-tests/src/tests/uniswap.rs
engine/Cargo.toml
etc/state-migration-test/Cargo.lock

This resolves security issues with `Signature::parse` functions
See https://github.com/paritytech/libsecp256k1/commit/b525d5d318d9672a40250c1725fa1bb3156688b7
Closes https://app.clickup.com/t/2c7n5yy

Build(deps): Upgrade `libsecp256k1` version 0.3.5 => 0.7.0

---

engine-precompiles/src/secp256k1.rs
engine-sdk/src/lib.rs
engine-tests/src/tests/ecrecover.rs
engine-tests/src/tests/mod.rs
engine-tests/src/tests/sanity.rs

While testing the Borealis engine by replaying mainnet history I found that [this transaction](https://aurorascan.dev/tx/0xd3ef40dfe6fc6daf25c86dc09cb1749a3ddef08acaccfd223599afc18cd08cb6) gave a different result in the standalone than it did when it executed on chain.
The on-chain execution failed with an error message about failing to validate a signature using `ecrecover`, whereas the standalone execution passed without error (ie `ecrecover` did not fail to validate the signature). This means the implementation of the precompile `0x01` is different in the standalone than in the wasm contract. This must be resolved.
So far in this PR I have only created a unit test to show there is a problem; I have not implemented a fix yet.

Standalone and wasm ecrecover implementations differ

---

engine-tests/src/test_utils/mod.rs
engine-tests/src/test_utils/one_inch/mod.rs
engine-tests/src/test_utils/standalone/mocks/mod.rs
engine-tests/src/tests/one_inch.rs
engine-tests/src/tests/repro.rs
engine-tests/src/tests/res/self_destructor.sol
engine-tests/src/tests/sanity.rs
engine-tests/src/tests/standalone/json_snapshot.rs
engine-tests/src/tests/uniswap.rs
engine/src/accounting.rs
engine/src/connector.rs
engine/src/engine.rs
engine/src/fungible_token.rs
engine/src/lib.rs

This PR fixes a bug where the total supply on Aurora (that is the amount of ETH available in the EVM) was incorrectly lowered if a self-destructed address had a beneficiary other than itself. In that case the funds were simply moved from one address to another without any being lost even though an account was deleted.
The fix is implemented by aggregating the changes to the ETH supply in each item of the `Apply` loop done at the end of an EVM transaction. In the case of a self-destruct with beneficiary, this accounting will see the tokens removed from the deleted account, but added to the beneficiary's account, thus correctly recognizing this as net zero change. If there was no beneficiary (eg the contract specifies itself), then there will be no other `Apply` entry to offset this loss …

Fix(engine): Correctly account for changes in total supply of ETH on Aurora

---

engine-precompiles/src/xcc.rs
engine-tests/src/tests/xcc.rs
engine-types/src/lib.rs
engine-types/src/types/gas.rs

Addresses https://github.com/aurora-is-near/aurora-engine/pull/560#discussion_r936952965

Feat(xcc): Estimate EVM gas cost for xcc precompile

---

Cargo.lock
engine-precompiles/Cargo.toml
engine-precompiles/src/account_ids.rs
engine-precompiles/src/blake2.rs
engine-precompiles/src/bn128.rs
engine-precompiles/src/hash.rs
engine-precompiles/src/identity.rs
engine-precompiles/src/lib.rs
engine-precompiles/src/modexp.rs
engine-precompiles/src/native.rs
engine-precompiles/src/prepaid_gas.rs
engine-precompiles/src/random.rs
engine-precompiles/src/secp256k1.rs
engine-standalone-storage/Cargo.toml
engine-standalone-tracing/Cargo.toml
engine-standalone-tracing/src/sputnik.rs
engine-standalone-tracing/src/types/call_tracer.rs
engine-tests/Cargo.toml
engine-tests/src/tests/repro.rs
engine-tests/src/tests/uniswap.rs
engine-transactions/Cargo.toml
engine-types/Cargo.toml
engine/Cargo.toml
etc/state-migration-test/Cargo.lock

Updates the engine to use the latest version of SputnikVM. This change is important because it adds new functionality to precompiles to allow them to make sub-calls. This will be useful in the upcoming cross-contract calls (xcc) feature.
In this PR we do not change our internal `Precompile` trait to expose the new functionality, this can be done as part of the xcc work. For now we just update all the dependencies so that we have access to this functionality within SputnikVM itself.
Since SputnikVM uses newer versions of the Ethereum types crates we also had to update a few other dependencies, including a welcome return to the official `ethabi` crate instead of a fork because the official one now has no-std support.
These updates also lead to a small performance improvement, as seen by the …

Chore(engine): Update to latest version of SputnikVM

---

.github/workflows/builds.yml
.github/workflows/lints.yml
.github/workflows/scheduled_lints.yml
.github/workflows/tests.yml

Very simply, this is updating [Checkout](https://github.com/actions/checkout) to v3, which simply updates to the node16 runtime.
None.
None.
As far as I could tell, there weren't any notably new features we could utilise, and this is more of a maintenance update. Would be good to double-check this.
None.

Chore(CI): Update checkout to version 3

---

engine-transactions/src/lib.rs

The engine was panicking on empty input to `subimt` ([example](https://explorer.mainnet.near.org/transactions/Hs4T5S8UsiKvtd2ajav4qPVEyZcfb9WagXDq6iGHLEK#Fu7UjCpmCj7fK3YYhsZbRubCJmC7kxBL8Z94ADh4exri)). This is not necessary, we can gracefully handle empty input.

Fix(engine-transactions): Prevent panic on empty input

---

engine/src/connector.rs
engine/src/lib.rs

The intent of the `get_bridge_prover` function is to return the account ID the engine uses to verify proofs coming from the bridge (used in transferring assets from Ethereum to NEAR). The account ID is stored in the eth-connector. In this PR, we fix the `get_bridge_prover` function to return the value from the eth-connector. I think this means the value in the engine state is unused, but it would be a bit of a pain to remove it (requires state migration to delete a field), so it is probably not worth the hassle.

Fix(engine): Return correct value for get_bridge_prover function

---

etc/eth-contracts/package.json
etc/eth-contracts/yarn.lock

This simply bumps Open Zeppelin contracts to 4.7.3 from 4.7.0.

Chore(eth-contracts): Update openzeppelin to 4.7.3

---

Cargo.lock
engine-standalone-storage/Cargo.toml
engine-standalone-storage/src/sync/types.rs
engine-types/src/types/address.rs
engine/src/engine.rs

The refiner is a tool that consumes raw NEAR blocks and creates "Aurora blocks" that contain information relevant to the Aurora contract on NEAR, and presented in a form that is compatible with Ethereum tooling.
However, it is inconvenient that the logic to map NEAR transactions on the Engine to Ethereum-like transactions is located in a separate repository to the Engine. In particular, it means there can be new functions added to the Engine which the refiner does not know about. This PR aims to fix this problem by adding logic to the standalone representation of transactions to convert them into normalized Ethereum transactions. This way, if the standalone engine `TransactionKind` is updated (and we still need to remember to do that whenever we add a new function on the Engine), then the …

Feat(standalone): Conversion from standalone's TransactionKind to NormalizedEthTransaction

---

.catalog-info.yaml
engine-precompiles/.catalog-info.yaml
engine/.catalog-info.yaml
etc/eth-contracts/.catalog-info.yaml

@sept-en Could you please review the precompiles piece and add description?
@joshuajbouw please check and feel free to add more info!

Add Backstage metadata

---

engine-transactions/Cargo.toml

I'm getting a compiler error when I try depending on aurora-engine-transactions crate with the `std` feature
```
error: failed to select a version for `aurora-engine-transactions`.
... required by this package
versions that meet the requirements `*` are: 1.0.0
this package depends on `aurora-engine-transactions`, with features: `hex` but `aurora-engine-transactions` does not have these features.
```
Looks like when `hex` was [removed as a dependency](https://github.com/aurora-is-near/aurora-engine/pull/571/files#diff-81b0e69f4699d48b8b5f461a5b37437bace7dbdf6fe003993ef0544a778d926aL21), the features also needed to be changed.
This PR fixes the issue.

Fix(aurora-engine-transactions): remove hex feaure from std

---

engine-tests/src/tests/eth_connector.rs

Adds some additional tests for the eth-connector. These tests illustrate the the connector works in a sensible way if someone tries to use an account other than the aurora-engine to receive ETH tokens.

Connector-tests: Add tests for the case where an account other than aurora-engine is used for ETH deposit

---

.github/workflows/tests.yml
Cargo.lock
engine-precompiles/src/alt_bn256.rs
engine-precompiles/src/blake2.rs
engine-precompiles/src/hash.rs
engine-precompiles/src/identity.rs
engine-precompiles/src/lib.rs
engine-precompiles/src/modexp.rs
engine-precompiles/src/secp256k1.rs
engine-standalone-storage/src/sync/mod.rs
engine-standalone-storage/src/sync/types.rs
engine-tests/Cargo.toml
engine-tests/src/test_utils/exit_precompile.rs
engine-tests/src/test_utils/mod.rs
engine-tests/src/test_utils/standalone/mod.rs
engine-tests/src/tests/mod.rs
engine-tests/src/tests/pausable_precompiles.rs
engine-tests/src/tests/repro.rs
engine-tests/src/tests/standard_precompiles.rs
engine-types/src/lib.rs
engine/Cargo.toml
engine/src/engine.rs
engine/src/lib.rs
engine/src/parameters.rs
engine/src/pausables.rs
etc/state-migration-test/Cargo.lock

Introduces pausable precompiles for stopping the engine when it hits a precompiled function. This is useful for emergency cases.
Increases gas cost by a few Tgas because of additional storage read operation to load the few bytes of paused precompiles flags.
Every added module is covered by a set of unit tests covering every conceived test scenario.
Then there is a module in `engine-tests` containing a set of functional tests that checks several test scenarios on the wasm binary. For example, there is a test case hitting a paused precompile during a smart contract execution that expects the error `ERR_PAUSED`. 
You should consider the administrative engine smart contract methods this feature is going to be controlled by. Take a look at test scenarios to get an idea. Separately from that, …

Pausable precompiles

---

Cargo.lock
engine-precompiles/Cargo.toml
engine-precompiles/src/lib.rs
engine-standalone-storage/src/sync/mod.rs
engine-test-doubles/src/io.rs
engine-test-doubles/src/promise.rs
engine/Cargo.toml
engine/src/engine.rs
engine/src/json.rs
engine/src/lib.rs
engine/src/pausables.rs

Increases unit test coverage of the `aurora-engine`.
None because these changes only affect tests.
Done by the tests included in the PR.
Aside from adding tests, there are some changes in `Engine` code to pay attention to.
The `Engine::view` function signature has been changed slightly for simpler testing. Even though it is public, I expect it to be only called from within `Engine` or the engine smart contract.
The `Engine::receive_erc20_tokens` had a parameter removed along with a bit of code. The bit of code was wrapped in a condition that would be always false. And the removed parameter was only used in this bit of code.

Test(engine): Increase unit test coverage

---

engine-sdk/src/near_runtime.rs
engine-sdk/src/promise.rs
engine-standalone-storage/src/promise.rs
engine-test-doubles/src/promise.rs
engine/src/engine.rs
engine/src/lib.rs
engine/src/xcc.rs

Creating promises on NEAR from the Engine account is dangerous because of the admin privileges it holds. In this PR we mark the functions which create promises as `unsafe` so that the Rust compiler will not let us use them outside of an `unsafe` block. The purpose of this change is to draw attention to new usages of these functions in the future. These functions must always be accompanied by a comment describing why it is safe to make a promise in that instance, and reviewers of the PR which introduces the new usage must verify the comment is accurate. This will hopefully make it more difficult for accidental security vulnerabilities to be introduced in the future.
This PR is purely a refactor; no functionality is changed.

Refactor: Mark functions that create promises on NEAR as unsafe

---

engine/src/lib.rs

In the xcc flow, we store the current version of each deployed sub-account in the Engine's storage. When a router contract is out of date (or the sub-account does not yet exist) then we must deploy the new version and update the entry in storage. The storage update is done as a callback after the deploy. In this PR we add logic to check the deploy was successful before updating the version in storage.
Existing xcc tests are used for testing (the deploy flow is tested because it occurs when creating a sub-account for the first time).

Fix(xcc): Only update the router contract version in storage if the deploy is successful

---

.github/workflows/lints.yml
Cargo.lock
Makefile.toml
engine-standalone-storage/Cargo.toml
engine-standalone-storage/src/engine_state.rs
engine-standalone-storage/src/lib.rs
engine-test-doubles/src/promise.rs
engine-tests/Cargo.toml
engine-tests/src/tests/one_inch.rs
engine-tests/src/tests/repro.rs
engine-tests/src/tests/uniswap.rs
engine-types/src/account_id.rs
engine/Cargo.toml
engine/src/deposit_event.rs
engine/src/engine.rs
engine/src/json.rs
rust-toolchain

Closes #612 
Upgrading rocksdb also requires updating the nearcore dependency in tests so that there is only one version of librocksdb-sys used. Updating nearcore required us to also update rust-toolchain since nearcore uses newer (v1.64.0) Cargo.toml features.
The newer version of rocksdb also changed the API for iterating over keys in the DB, this is why there is now extra error handling in `engine-standalone-storage`.

Chore(standalone): Upgrade rocksdb to v0.19.

---

.github/workflows/builds.yml
.github/workflows/tests.yml

The CI is currently broken, and according to @strokovok it fails with [sscache](https://lib.rs/crates/sccache). Removing this should get it running again. Right now it is quite unclear why it is hanging here and may be some issue with our own build servers.

fix: remove sscache from CI

---

Cargo.lock
engine-precompiles/Cargo.toml
engine-precompiles/src/promise_result.rs
engine-standalone-storage/Cargo.toml
engine-standalone-tracing/Cargo.toml
engine-test-doubles/Cargo.toml
engine-tests/Cargo.toml
engine-tests/src/tests/repro.rs
engine-tests/src/tests/res/CallTooDeep.sol
engine-tests/src/tests/sanity.rs
engine-tests/src/tests/uniswap.rs
engine-transactions/Cargo.toml
engine/Cargo.toml

This PR is related to issue #627 . In this PR I add a test illustrating the problem outlined in that issue. Once this test passes, we know the issue is resolved.
A new test includes an infinitely recursive Solidity contract. The point of this test is to create a situation where the EVM call stack limit is exceeded and see how the engine behaves. Presently the test is failing (per the issue described in #627 ), but once it passes then we should merge this PR.
The fix itself will be in SputnikVM, not in the Engine. I'll make a PR in that repo and reference this PR in it.

Feat(tests): Test for trying to obtain TransactionStatus::CallTooDeep from the Engine

---

engine-precompiles/src/xcc.rs
engine-tests/src/tests/xcc.rs
engine-types/src/parameters.rs

While working on the native token connector, I found that I could not eagerly execute promises with callbacks using the XCC mechanism. It turned out this was because the XCC precompile was not attaching enough NEAR gas to the router's `execute` function when there are promises involved. The amount of gas needed scales linearly with the number of callbacks. This PR fixes the issue and the XCC precompile now accounts for the linearly increasing amount of gas needed for promises with callbacks.
I've updated `test_xcc_exec_gas` to loop through promises with different numbers of callbacks.

Fix(xcc): Ensure the xcc router attaches enough gas to the execute function

---

engine-precompiles/src/alt_bn256.rs

A regression was found from the last update where bn256 doesn't think that 0,0 is on the curve so it results in a revert. This fixes this issue.
None.
I conducted a test which uses only 0,0 points in bn256 pair to show that the fix has been made and can't be regressed again.
Key points is that the fix has been made simply.
This was reported by BlockSec and must make it into the 2.8 release.

fix: bn256 regression

---

Cargo.lock
engine-precompiles/Cargo.toml
engine-standalone-storage/Cargo.toml
engine-standalone-tracing/Cargo.toml
engine-standalone-tracing/src/types/call_tracer.rs
engine-test-doubles/Cargo.toml
engine-tests/Cargo.toml
engine-tests/src/test_utils/standalone/mod.rs
engine-tests/src/tests/mod.rs
engine-tests/src/tests/standalone/call_tracer.rs
engine-tests/src/tests/standalone/mod.rs
engine-tests/src/tests/xcc.rs
engine-transactions/Cargo.toml
engine/Cargo.toml

There was a bug introduced in SputnikVM `v0.37.1-aurora` where some `Exit` tracing events were missing, which caused the tracing feature not to work correctly. This was fixed in `v0.37.3-aurora`. In this PR we update to the fixed version and add new tests to prevent such a regression in the future.
New tests for tracing.

Fix(tracing): update to SputnikVM `v0.37.3-aurora`

---

Cargo.lock
engine-precompiles/Cargo.toml
engine-standalone-storage/Cargo.toml
engine-standalone-tracing/Cargo.toml
engine-standalone-tracing/src/sputnik.rs
engine-standalone-tracing/src/types/call_tracer.rs
engine-test-doubles/Cargo.toml
engine-tests/Cargo.toml
engine-tests/src/tests/standalone/call_tracer.rs
engine-transactions/Cargo.toml
engine/Cargo.toml

EVM tracing is expected to include the code deployed during a `CREATE`/`CREATE2` operation (see for example the `code` field in https://docs.alchemy.com/reference/what-are-evm-traces#create ). This PR updates to a newer version of SputnikVM where I have added this functionality and includes a test for it.
Note: this PR does not impact the Aurora Engine smart contract, only the tracing functionality which is used by the standalone engine.
New test for tracing a contract deploy transaction.

Feat(tracing): include deployed code in trace output for CREATE

---

engine/src/pausables.rs

The PR adds tiny optimisation by removing unnecessary dynamic memory allocation while creating precompile flags from storage value.

chore: remove dynamic memory allocation while creating precompile flags

---

engine-standalone-storage/src/relayer_db/mod.rs
engine-standalone-storage/src/sync/mod.rs
engine-tests/src/test_utils/standalone/mocks/mod.rs
engine-tests/src/tests/sanity.rs
engine-tests/src/tests/standalone/sanity.rs
engine/src/engine.rs
engine/src/lib.rs
engine/src/state.rs
etc/tests/self-contained-5bEgfRQ/src/lib.rs
etc/tests/state-migration-test/src/lib.rs

Simply refactors the state into its own module. My motivation is to improve the code quality gradually when required.
Ensure that the refactor is complete, and nothing that has been missed was missed. That would require looking into the `engine/src/engine.rs` and ensuring all relevant tests and anything to do with the state has been moved.
Descoped from a scope creeping PR https://github.com/aurora-is-near/aurora-engine/pull/662

chore(state): refactor state into module

---

engine-test-doubles/src/io.rs
engine-tests/src/tests/standalone/sanity.rs
engine/src/connector.rs
engine/src/engine.rs
engine/src/lib.rs
engine/src/map.rs
engine/src/pausables.rs
engine/src/state.rs

The PR just replaces `RwLock` with `RefCell` in a `StoragePointer` struct. It seems that `RefCell` is pretty enough in this case. 
The changes touch test code only, so there is no regression.
All tests have been passed.

chore: replace RwLock for RefCell in storage for tests

---

engine-sdk/src/lib.rs

Continuing with trying to make `aurora-engine-types` usable as a library for other Near contracts, I am proposing we remove this unstable feature. It doesn't seem to have any impact on the code (everything compiles and tests still pass), and removing it allows the crate to compile with stable rust.

Chore: Remove unused alloc_error_handler feature

---

Cargo.lock
engine-sdk/Cargo.toml
engine-sdk/src/base64.rs
engine-sdk/src/lib.rs
engine-standalone-storage/Cargo.toml
engine-standalone-storage/src/json_snapshot/mod.rs
engine-standalone-storage/src/lib.rs
engine-tests/Cargo.toml
engine-tests/src/test_utils/mod.rs
engine-tests/src/tests/standalone/json_snapshot.rs
engine/Cargo.toml
engine/src/fungible_token.rs

The PR updates some rust dependencies and extends `aurora-engine-sdk` crate with two functions for base64 en/decoding.

chore: update some rust dependencies

---

engine-tests/src/tests/sanity.rs
engine/src/engine.rs

A bug was found where we increment the nonce when a user is `OutOfFund`. After looking into it, there were some other areas where the nonce could be incremented incorrectly. As far as I can tell, with these changes, this shouldn't affect internal services, but that needs to be checked ideally by @birchmd.
No gas increases, though a slight reduction should be possible.
Tests were updated for this fix.
While the fix should be correct, it should be checked that this is fine for internal services.

fix: incremented nonce on out of fund failure

---

Cargo.lock
Cargo.toml
Makefile.toml
engine-standalone-nep141-legacy/Cargo.toml
engine-standalone-nep141-legacy/src/admin_controlled.rs
engine-standalone-nep141-legacy/src/fungible_token.rs
engine-standalone-nep141-legacy/src/legacy_connector.rs
engine-standalone-nep141-legacy/src/lib.rs
engine-standalone-storage/Cargo.toml
engine-standalone-storage/src/relayer_db/mod.rs
engine-standalone-storage/src/sync/mod.rs
engine-standalone-storage/src/sync/types.rs
engine-tests/Cargo.toml
engine-tests/src/test_utils/mod.rs
engine-tests/src/test_utils/standalone/mocks/mod.rs
engine-tests/src/test_utils/standalone/mod.rs
engine-tests/src/tests/standalone/sync.rs
engine-types/src/storage.rs
engine/src/admin_controlled.rs
engine/src/connector.rs
engine/src/lib.rs
engine/src/parameters.rs

After splitting logic in #607 - Split NEP-141 from Engine, `engine-standalone` requires changes. Since `engine-standalone` cannot interact with the new `aurora-eth-connectpr` contract, the previous NEP-141-related codebase has been moved separately to `standalone-nep141-legacy`. This will ensure that `engine-standalone` works well with historical data.
Modules were added:
- `legacy_connector`
- `fungible_token`
It affects only standalone. So no side effects.
Tests not changed for standalone. Just restored expected behaviour. For some unknown reason failed function `validate_standalone`, but that function don't affect any test.

Feat: standalone nep141 legacy

---

engine-sdk/src/near_runtime.rs
engine-sdk/src/promise.rs
engine/src/lib.rs
etc/xcc-router/src/lib.rs

On Near every promise in a chain of callbacks will execute regardless of the success/failure of previous promises in the chain. We need to explicitly check for success of past promises before continuing.
This is pretty tricky to test because we already had many checks in place to ensure that promises would not be failing before executing the chain in the first place. These checks are mostly a safety net for if something totally unexpected occurs. My standpoint is that if this change doesn't break any of the existing xcc tests then it should be ok. The code is simple enough that a careful review should reveal any problems with it.

Fix: check promise results before executing XCC callbacks

---

engine/src/engine.rs

We're going to allow XCC on mainnet starting with the next Engine release! 🚀

Feat: enable XCC on mainnet

---

Makefile.toml
engine-standalone-tracing/src/sputnik.rs
engine-test-doubles/src/promise.rs
engine-tests/src/benches/eth_deploy_code.rs
engine-tests/src/test_utils/mod.rs
engine-tests/src/test_utils/standalone/mocks/mod.rs
engine-tests/src/tests/erc20_connector.rs
engine-tests/src/tests/sanity.rs
engine-tests/src/tests/standalone/sanity.rs
engine-tests/src/tests/standalone/storage.rs
engine-tests/src/tests/standalone/tracing.rs
engine-tests/src/tests/xcc.rs

The PR applies changes proposed by clippy with `as_conversions` lint on.

chore: apply clippy::as_conversions lint to all sub-crates

---

engine-tests/Cargo.toml
engine-tests/src/tests/mod.rs
engine-tests/src/tests/serde.rs
engine-types/src/parameters/engine.rs
engine/src/engine.rs

In PR #677 we made `serde` required instead of optional in `aurora-engine` and `aurora-engine-types`. This change means the `serde` feature no longer exists and this prevents the serde traits from being derived on several types. In this PR I fix this regression by using the `impl-serde` feature to trigger deriving the traits instead. I also add new tests which will catch this problem in the future.

Fix: re-enable deriving serde traits

---

engine/src/engine.rs

Avoid panicking `receive_erc20_tokens()` in`hex::decode()` to propagate any errors.

fix: reachable panic in `receive_erc20_tokens()`

---

engine-precompiles/src/alt_bn256.rs
engine-types/src/types/gas.rs

In engine-types, the `EthGas` struct does not perform checks on division by `0` in its `Div` implementation.

fix: Lack of Division by `0` Checks In `EthGas::Div()`

---

engine-precompiles/src/alt_bn256.rs

fix: check inputs in `alt_bn256`

---

Cargo.lock
Makefile.toml
engine-precompiles/Cargo.toml
engine-sdk/Cargo.toml
engine-standalone-storage/Cargo.toml
engine-tests/Cargo.toml
engine-tests/src/tests/erc20_connector.rs
engine-tests/src/tests/sanity.rs
engine-tests/src/tests/xcc.rs
engine-types/Cargo.toml
engine-types/src/account_id.rs
engine-types/src/parameters/engine.rs
engine-types/src/parameters/mod.rs
engine-types/src/storage.rs
engine-types/src/types/address.rs
engine-types/src/types/balance.rs
engine-types/src/types/fee.rs
engine-types/src/types/gas.rs
engine-types/src/types/mod.rs
engine-types/src/types/wei.rs
engine/Cargo.toml
etc/tests/self-contained-5bEgfRQ/Cargo.toml
etc/tests/state-migration-test/Cargo.toml
etc/xcc-router/Cargo.lock
etc/xcc-router/Cargo.toml

This PR updates the Engine contract to use borsh version 0.10. This is needed because [nearcore now uses borsh v0.10](https://github.com/near/nearcore/blob/a6d14feb03af14912f9c6d41857fd4013c8654b8/Cargo.toml#L92) and [borealis-engine-lib](https://github.com/aurora-is-near/borealis-engine-lib) must use both Engine and nearcore types in the same project.
Unfortunately there is a complexity here where the latest [near-sdk still depends on borsh v0.9](https://github.com/near/near-sdk-rs/blob/89f8c2d776c8d00feb45239fdb15725527f1894b/near-sdk/Cargo.toml#L27). Therefore the `aurora-engine-types` crate which is used with near-sdk in some other Near contracts (for example XCC router), actually must support both versions of borsh until there is a new release of near-sdk. This is accomplished by …

Chore: update to borsh version 0.10

---

engine-precompiles/src/modexp.rs
engine-tests/src/tests/modexp.rs

EVM precompiles generally do not return errors; they take whatever input users give and do their best to return a sensible output. For example
```
go-ethereum$ ./build/bin/evm \
--input 0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000c000000000000000000000000000000000000000000000000000000000000000071000000000000ff600000000000000000000000000000000000000000000000 \
--receiver 0x0000000000000000000000000000000000000005 \
run
0x
```
We see this input calls `modexp` with the size of both base and modulus both equal to zero, and the size of the exponent equal to `u64::MAX`. Since the `modexp` precompile output is bounded by the size of the modulus, we know the output is empty because the size of the modulus is …

Fix(modexp): do not return an error when length cannot be cast to usize

---

engine/src/engine.rs
engine/src/lib.rs

The PR allows using an owner account in the `EngineAuthorizer` rather than a hardcoded `aurora` account.
There should be no changes in the performance.

chore: use owner account in engine authorizer

---

engine-standalone-storage/src/sync/mod.rs
engine-standalone-storage/src/sync/types.rs
engine-tests/src/tests/xcc.rs
engine/src/lib.rs
engine/src/xcc.rs

The purpose of this PR is to add a new function to the Engine for creating XCC sub-accounts that are funded from an external Near account. The reason this is useful is because it allows the XCC feature to be used in an instance of the Engine where the wNEAR token has not been bridged (this is not the case on mainnet `aurora`, but could be the case on other Engine instances).
Note: this allows creating XCC accounts without requiring the Engine to know about wNEAR, but if a user wants to attach NEAR to their cross-contract calls then then Engine (and that user) will still need wNEAR. This should not be too much of a limitation since many things can be done on Near without spending the base token.
One new XCC test to show this works to create a sub-account and use it for XCC in an Engine …

Feat: allow creating and funding XCC sub-accounts from external NEAR accounts

---

engine-tests/src/tests/state_migration.rs
engine/src/lib.rs

There is an issue in `deploy_upgrade()` that the upgrade index is not cleared after each call.
Therefore, `deploy_upgrade() `will pass the check `io.block_height() <= index + state.upgrade_delay_blocks` since
`index` remains unchanged from previous calls.

Fix: deploy_upgrade() Does Not Clear Upgrade Index 

---

engine-standalone-storage/src/lib.rs
engine-standalone-tracing/src/types/mod.rs

Several instances of lack of array bounds checks were identified in the `engine-standalone-storage` and `engine-standalone-tracing` crates.
**Recommendations**
Implement checks to ensure values used when slicing arrays or referencing items from arrays are within array bound- aries.
Use safer alternatives, such as `.get(n..m)` or `.get_mut(n..m) `when accessing array elements.

Fix: Lack of Checks of Array Bounds

---

Cargo.lock
engine-precompiles/Cargo.toml
engine-precompiles/src/prelude.rs
engine-precompiles/src/promise_result.rs
engine-precompiles/src/xcc.rs
engine-sdk/Cargo.toml
engine-sdk/src/io.rs
engine-sdk/src/prelude.rs
engine-standalone-storage/Cargo.toml
engine-standalone-storage/src/diff.rs
engine-standalone-storage/src/sync/types.rs
engine-tests/src/test_utils/erc20.rs
engine-types/src/lib.rs
engine/Cargo.toml
engine/src/connector.rs
engine/src/deposit_event.rs
engine/src/fungible_token.rs
engine/src/lib.rs
engine/src/parameters.rs
engine/src/pausables.rs
engine/src/prelude.rs
engine/src/proof.rs
engine/src/state.rs
engine/src/xcc.rs

[Near Workspaces](https://crates.io/crates/workspaces) still uses `borsh` version 0.9. Therefore we need the `borsh-compat` feature on all our crates that use `borsh` if we want to use them in Workspaces-based tests. This PR makes this change.
This is a non-functional change (impacts only a dependency version and only if a feature is specified), therefore has no impact on tests or performance.

Fix: use single crate for borsh version, allow to choose borsh v0.9 for all crates

---

.github/CODEOWNERS

hskang9 is no longer part of the company, so removing him as one of the listed code owners. For now, I'll take ownership over tests libraries and in the future, may pass on ownership to another.

chore(github): remove hskang9 from CODEOWNERS

---

.github/workflows/lints.yml
.github/workflows/tests.yml
Makefile.toml

The goal of the PR is to speed up passing CI flow. Also, it adds an additional job for testing the `bech_modexp` flow.

chore: add bench-modexp flow to CI script

---

engine-modexp/Cargo.toml
engine-modexp/src/lib.rs
engine-tests/src/tests/modexp.rs
engine-tests/src/tests/repro.rs

Switch to using the `ibig` implementation for modexp. Its performance is better than current Aurora implementation in some (but not all) cases, and it is more battle-tested in terms of correctness.

Fix(modexp): use ibig implementation

---

CHANGES.md

Adding links was missed in the changelog for 2.9.2 release, adding in those now.

chore: fix changelog links for 2.9.2

---

engine-tests/src/tests/erc20.rs
engine-transactions/src/lib.rs
engine/src/engine.rs

Engine is configured with Shanghai hardfork now. No other changes.
N/A
N/A
N/A
N/A

fix: use shanghai config instead of london

---

.github/workflows/tests.yml
scripts/ci/build_rocksdb.sh

Compiling the `rocksdb` crate consumes a lot of time because it compiles `librocksdb.a` library under the hood. The PR adds additional flow in CI to precompile this library and save it into the cache for further re-using.

chore: precompile librocksdb for speed up tests

---

Cargo.lock
Cargo.toml
engine-modexp/Cargo.toml
engine-precompiles/Cargo.toml
engine-sdk/Cargo.toml
engine-standalone-storage/Cargo.toml
engine-standalone-tracing/Cargo.toml
engine-test-doubles/Cargo.toml
engine-tests/Cargo.toml
engine-transactions/Cargo.toml
engine-types/Cargo.toml
engine/Cargo.toml

The PR adds the possibility to define crate versions used in all crates in the monorepo in `workspace.depdndencies` section of the main `Cargo.toml` file.

chore: use workspace dependencies

---

Cargo.lock
engine/Cargo.toml
engine/src/deposit_event.rs

The PR removes the redundant `byte-slice-cast` crate from `aurora-engine` as it is used only in one place in the code. Also, vectors have been replaced by fixed-size arrays.
No performance changes.
It doesn't require adding new tests.

chore: get rid of the byte-slice-cast crate in engine

---

.github/workflows/tests.yml
engine/src/lib.rs

Given that there are precautions to remove a staged upgrade, and only the owner or DAO can stage an upgrade, removing the owner's requirement of deploying the upgrade is safe.
We started running into a potential issue where it may be too costly for the DAO to deploy future Engine releases. While there is currently no issue to stage a release, a deployment may, in fact be a bit too costly. The DAO almost hit this limit previously as 280 Tgas was the gas required via the DAO. Additionally, this reduces the DAO votes by 1 as now they only have to vote on an upgrade which needs to be staged.
This should be done as a patch release on the master branch prior to any further deployments.

feat: remove owner requirement on deploying a staged upgrade

---

.github/workflows/builds.yml

The PR adds regular expression for validating tags which correspond semver rules. E.g. `2.10.1`. Only such tags will be triggered a build flow.

ci: use semver regular expression for tag

---

Cargo.lock
engine-tests/src/tests/sanity.rs

The PR bumps the `sputnikvm` version, which contains a bugfix of the `shanghai` implementation.
Added test which validates EVM transaction created with parameter: `evmVersion: 'shanghai'`.

fix: push0 should increment program counter by 1 instead of 2

---

Cargo.lock
engine-tests/src/tests/xcc.rs
engine-workspace/src/contract.rs
engine-workspace/src/operation.rs
engine/src/lib.rs

The PR adds a function for returning factory wNEAR address in borsh format.

feat: add function to return wNEAR address

---

engine-modexp/Cargo.toml
engine-modexp/src/lib.rs
engine-tests/src/tests/modexp.rs
engine-tests/src/tests/repro.rs

With the improvements from #809 merged, we can start using the Aurora implementation of modexp.
There is a gas cost increase in one of the repro tests. This must mean the `ibig` implementation of modexp is faster for the case used in that transaction. But using the Aurora implementation of modexp is still an improvement because the worst-case performance of the Aurora implementation is better than `ibig`, as exemplified in the `bench_modexp_standalone` test.
Existing tests.

Fix(modexp): re-enable Aurora implementation

---

Cargo.lock
Cargo.toml
engine-standalone-storage/Cargo.toml
engine-standalone-storage/src/error.rs
engine-standalone-storage/src/sync/mod.rs
engine-standalone-storage/src/sync/types.rs
engine-tests/src/tests/contract_call.rs
engine-tests/src/tests/erc20_connector.rs
engine-tests/src/tests/modexp.rs
engine-tests/src/tests/pausable_precompiles.rs
engine-tests/src/tests/pause_contract.rs
engine-tests/src/tests/repro.rs
engine-tests/src/tests/sanity.rs
engine-tests/src/tests/xcc.rs
engine-tests/src/utils/mod.rs
engine-tests/src/utils/standalone/mocks/mod.rs
engine-tests/src/utils/standalone/mod.rs

This is the first in a series of PRs that is meant to split up #705 . The idea is to merge the changes which are made in that PR in logical chunks until eventually the whole hashchain implementation is in. Doing the work in smaller pieces will both make it easier to review and prevent us from needing to maintain large, long-lived feature branches.
This first PR pulls in the transaction transaction parsing logic from [borealis-engine-lib](https://github.com/aurora-is-near/borealis-engine-lib) into this repo (in a future PR we will remove the duplicated code from borealis-engine-lib). The logic is used here to simplify how transactions are handled in tests because all transactions can automatically be passed to both the Near runtime (processed by the Engine as Wasm) and the standalone …

Feat(standalone): logic for parsing TransactionKind from raw Near data

---

engine-modexp/src/mpnat.rs
engine-tests/src/tests/repro.rs

- Fixes a panic with empty exponent
- Ensure correct result with zero exponent
- Fix performance issues with exponents with large zero padding
The performance is increased for some cases (those with exponents with a large amount of leading zeroes) and remains the same for all other cases.
Fuzzing and tests added.

`engine-modexp` bug fixes and performance improvements with unusual exponents

---

Cargo.lock
Cargo.toml
engine-hashchain/Cargo.toml
engine-hashchain/src/bloom.rs
engine-hashchain/src/error.rs
engine-hashchain/src/hashchain.rs
engine-hashchain/src/lib.rs
engine-hashchain/src/merkle.rs
engine-hashchain/src/tests.rs

This PR continues the effort of merging #705 in multiple pieces.
This PR introduces the core hashchain logic as a library crate. The reasons to factor the code in this way are:
1. Allows this PR to be safely merged because it has no impact on existing engine code
2. The same core logic will be reusable between components that will perform the hashchain computation in the future, namely: Aurora Engine smart contract, standalone engine, Borealis Refiner.
In the next PR I'll pull in the changes from #705 which actually introduce the hashchain calculation into the Aurora Engine smart contract and standalone engine.
N/A
New hashchain tests

Feat: core hashchain logic

---

Cargo.lock
Cargo.toml
Makefile.toml
engine-precompiles/src/promise_result.rs
engine-tests/src/tests/one_inch.rs
engine-tests/src/tests/repro.rs
engine-tests/src/tests/sanity.rs

Updates to the latest version of SputnikVM. There are two improvements:
- A fix to a bug in the `returndatacopy` op code implementation.
- An improvement in performance of accessing the EVM memory.
Several gas costs went down a little due to the improved performance in accessing the EVM memory.
For some reason this also causes the EVM gas cost of the promise results precompile to increase. I am not sure why, but it's only a small increase (recall that any EVM transaction must spend at least 21000 gas), so I think's ok.
New regression test for the `returndatacopy` bug.
New regression test for the EVM memory performance.

Chore: Update to SputnikVM version 0.38.3

---

engine-standalone-storage/src/sync/mod.rs
engine-tests/src/tests/standalone/sync.rs

The [Borealis refiner](https://github.com/aurora-is-near/borealis-engine-lib/tree/main/refiner-lib) was experiencing a performance issue where it would become very slow at processing blocks. Profiling revealed the reason was increasing time to look up the `ENGINE_STATE` key when replaying transactions (this replay is necessary to correctly process batch transactions on Near). After some investigation, we realized the cause of this slow lookup was due to that key being constantly written and deleted by every transaction. The reason for this churn is because the Engine logic was changed to automatically migrate its state, but of course old transactions did not have that logic and therefore the replay would compute an incorrect state diff relative to what is reported in the Near block. In …

Fix(standalone): Do not eagerly commit transactions to the DB

---

CHANGES.md
engine-precompiles/src/lib.rs
engine-precompiles/src/native.rs
engine-standalone-storage/src/sync/mod.rs
engine-tests-connector/src/utils.rs
engine-tests/src/utils/mod.rs
engine-tests/src/utils/standalone/mocks/mod.rs
engine-tests/src/utils/workspace.rs
engine-types/src/parameters/connector.rs
engine-types/src/storage.rs
engine-workspace/src/contract.rs
engine/src/admin_controlled.rs
engine/src/connector.rs
engine/src/lib.rs

The PR fixes the exit to ethereum precompile.
There are no changes in performance.
There are no tests for testing this part of the code, but it would be nice to have.

fix: fix in the exit_to_eth precompile

---

engine/src/contract_methods/mod.rs

This is needed to allow `ContractError` to be used easily in async Rust applications.
N/A
Existing tests.

Chore: make ContractError Send + Sync

---

Cargo.lock
Cargo.toml
engine-standalone-storage/src/error.rs
scripts/ci/build_rocksdb.sh

The `rocksdb` crate has been updated up to 0.21 in the nearcore 1.36.0-rc.1.

chore: bump rocksdb up to 0.21

---

CHANGES.md
engine-tests/src/tests/erc20.rs
engine-tests/src/tests/sanity.rs
engine/src/contract_methods/connector/mod.rs
engine/src/pausables.rs

The PR fixes behaviour when the owner of the smart contract can't set ERC-20 metadata in case the account id of the owner and the account id of the contract are different.
There are no changes in the performance.
The corresponding test has been added.

fix: setting erc-20 metadata by the owner of the contract

---

Cargo.lock
Cargo.toml
engine-tests-connector/Cargo.toml
engine-tests-connector/src/connector.rs
engine-tests-connector/src/utils.rs
engine-tests/src/tests/access_keys.rs
engine-tests/src/tests/erc20_connector.rs
engine-tests/src/tests/erc20_mirror.rs
engine-tests/src/tests/sanity.rs
engine-tests/src/tests/silo.rs
engine-tests/src/tests/xcc.rs
engine-tests/src/utils/workspace.rs
engine-workspace/Cargo.toml
engine-workspace/src/account.rs
engine-workspace/src/lib.rs
engine-workspace/src/macros.rs
engine-workspace/src/node.rs
engine-workspace/src/transaction.rs

The PR updates the `near-workspaces-rs` dependency.

deps: bump near-workspaces-rs to 0.9

---

engine-standalone-storage/src/relayer_db/mod.rs
engine-standalone-storage/src/sync/mod.rs
engine-standalone-storage/src/sync/types.rs
engine-tests/src/tests/random.rs
engine-tests/src/tests/repro.rs
engine-tests/src/tests/sanity.rs
engine-tests/src/tests/standalone/call_tracer.rs
engine-tests/src/tests/standalone/storage.rs
engine-tests/src/tests/standalone/sync.rs
engine-tests/src/tests/standalone/tracing.rs
engine-tests/src/utils/mod.rs
engine-tests/src/utils/standalone/mod.rs

The Near runtime has a random value available to smart contracts via a cost function. Aurora exposes that random value to EVM smart contracts in two ways: (1) via a custom precompile, and (2) via [EVM opcode 0x44](https://www.evm.codes/#44?fork=shanghai) since it was changed from `DIFFICULTY` to `PREVRANDAO` after the merge. Therefore it is important for the standalone engine to be able to correctly provide the same random value as would be present on-chain.
In this PR I fix the standalone engine to be able to correctly reproduce the Near runtime random value based on the implementation present in nearcore. There will also be a follow-up PR to `borealis-engine-lib` to make use of this change in the Borealis Engine there.
The random value is computed as `sha256(block_random_value || …

Fix(standalone): properly compute runtime random value

---

engine-precompiles/src/xcc.rs
engine-standalone-storage/src/sync/mod.rs
engine-standalone-storage/src/sync/types.rs
engine-types/src/parameters/xcc.rs
engine/src/contract_methods/evm_transactions.rs
engine/src/contract_methods/xcc.rs
engine/src/lib.rs
engine/src/xcc.rs

The XCC feature was designed to allow users to spend their own wNEAR ERC-20 tokens on Aurora in Near native interaction as if it were the base token. This works by bridging the wNEAR from Aurora out to the user's XCC account, then unwrapping it. The Rainbow bridge team noticed an issue where it is possible for the `wrap.near:withdraw_near` promise to resolve before the `wrap.near:ft_transfer` promise. This causes the XCC flow to fail if the user's XCC account does not carry a wNEAR balance because we attempt to withdraw tokens we don't yet have.
This PR aims to solve that issue. To see why this fix works, we need to know why the issue happens in the first place. The problem is the XCC flow used to use the `call` entry point to trigger the exit to Near function on the wNEAR ERC-20 token. …

Fix(xcc): Ensure near_withdraw comes after ft_transfer

---

engine-precompiles/src/native.rs

If `input` is empty a panic occurs. This PR sets `flag` to the default value in that case.
Fuzzing.
Ensure that `flag` assuming the default value if `input` is empty is the intended behavior.

Fix panic in ExitToNear

---

engine-sdk/src/near_runtime.rs
engine-sdk/src/promise.rs
engine-standalone-storage/src/promise.rs
engine-test-doubles/src/promise.rs
engine/src/engine.rs
engine/src/xcc.rs

This PR is addressing a [usability issue with XCC](https://github.com/aurora-is-near/aurora-contracts-sdk/pull/13#discussion_r1329912329) brought up by @karim-en .
It is somewhat common that XCC requires tokens to be bridged from the user's Aurora address to their XCC account on Near. Naturally, this bridging needs to happen before the XCC promise resolves so that the tokens are available for it to use. However, due to the async nature of Near we could not guarantee that the bridging would happen before the XCC call.
In this PR we change how the Engine produces promises so that they are sequential instead of concurrent (i.e. all the promises produced by the EVM are connected by the `then` combinator, in the order they were produced during the EVM execution). This means a contract which …

Feat: Exit and XCC promises are sequential

---

engine-standalone-storage/src/sync/mod.rs
engine/src/contract_methods/connector/external.rs
engine/src/contract_methods/connector/internal.rs
engine/src/contract_methods/connector/mod.rs
engine/src/engine.rs

Explorers like Blockscout rely on EVM logs to index certain events such as ERC-20 token transfers/minting/burning. When NEP-141 tokens are bridged to Aurora via `ft_on_transfer` there are ERC-20 token events that should be produced and indexed by explorers. This PR changes how `ft_on_transfer` calls are handled to expose the EVM logs generated to the standalone engine, which in turn will make them available to the Refiner and thus also to block explorers.
There will be a follow-up PR in `borealis-engine-lib` which uses the `SubmitResult` to include logs in the transactions corresponding to `ft_on_transfer`.
N/A no significant changes to contract code
Existing tests. (A new test will be added to `borealis-engine-lib` when we do integration there)

Feat(standalone): SubmitResult from bridge transactions is available

---

Cargo.toml
engine-tests/src/tests/sanity.rs
engine-types/src/parameters/engine.rs

The PR adds a new option to pass init arguments in JSON format. 
There are no changes in performance or gas cost.
A corresponding unit test has been added.
The controller contract needs the change to allow passing generic JSON object as initialise arguments.

feat: add possibility to provide new arguments in json format

---

engine-types/src/parameters/xcc.rs
engine/src/xcc.rs

In #866 I introduced a change to the XCC router where the contract became upgradable. In that PR I hardcoded that any XCC Router that was version 1 could not be upgraded, however this logic did not work on testnet where the XCC Router code had already been set twice, so it was actually version 3 which became the first upgradable version.
In this PR I add a new key to the engine which stores the first upgradable XCC version so that it does not need to be hardcoded. This should allow the logic to work properly on both testnet and mainnet.
N/A
Existing tests + testnet deployment (manual test)

Fix(xcc): Store the first upgradable XCC version in state

---

.github/workflows/builds.yml

The PR replaces the `self-hosted` runner with a `github-hosted-heavy-runner` in the build script to resolve this [issue](https://github.com/aurora-is-near/aurora-engine/actions/runs/7116977531/job/19376842569#step:4:35).

ci: replace self-hosted runner with github in the build script

---

.github/workflows/tests.yml
Cargo.lock
Cargo.toml
etc/tests/fibonacci/Cargo.toml
etc/tests/ft-receiver/Cargo.toml
etc/tests/modexp-bench/Cargo.toml
etc/xcc-router/Cargo.toml

The PR fixes building by replacing the usage of the `parity-secp256k1` crate from crates.io to github.

fix: use parity-secp256k1 crate from github

---

engine-precompiles/src/modexp.rs

In `calc_iter_count()`, which is part of the modexp precompile gas calculation, the most-significant bit of the exponent is added to the intermediate result. The MSB is computed using `U256::from(exp.bits()) - U256::from(1))` in:
```rust
Ok(U256::from(8) * U256::from(exp_len - 32) + U256::from(exp.bits()) - U256::from(1))
```
This works only if the exponent is non-zero; subtracting `1` from zero results in an underflow, leading to inaccurate gas requirements for specific inputs.
Geth computes the MSB [as follows](https://github.com/ethereum/go-ethereum/blob/fa0df76f3cfd186a1f06f2b80aa5dbb89555b009/core/vm/contracts.go#L340); notice the condition `bitlen > 0`:
```go
var msb int
if bitlen := expHead.BitLen(); bitlen > 0 {
msb = bitlen - 1
}
```
This PR changes the underflowing subtraction …

Fix underflow in modexp gas calculation

---

engine-tests-connector/src/connector.rs
engine-tests/src/tests/erc20_connector.rs
engine-tests/src/tests/standalone/sync.rs
engine-tests/src/utils/standalone/mocks/mod.rs
engine/src/contract_methods/connector/deposit_event.rs
engine/src/contract_methods/connector/external.rs
engine/src/contract_methods/connector/internal.rs
engine/src/contract_methods/connector/mod.rs

Remove unused and redundant `Fee` logic of the eth-connector.
The primary purpose of this change is to unify the message format for transferring ERC20 and native base tokens.
These changes should simplify the interactions with silo contracts, especially when the base token is an ERC20 token.
Slight reduction in gas
Added unit and workspace tests
Verify the `ft_on_transfer` logic for both internal and external connectors.
This change should be backward compatible, not breaking any internal or external components/services.
N/A

Remove eth-connector fee logic

---

Cargo.lock
engine-tests/src/tests/sanity.rs
engine-tests/src/tests/silo.rs
engine-tests/src/utils/mod.rs
engine/src/engine.rs
etc/xcc-router/Cargo.lock

The PR changes the incorrect panic message by adding values of an account nonce and a nonce from a transaction.
No changes in performance.
Correspondent tests have been adapted.

feat: improve incorrect nonce panic message

---

engine/src/contract_methods/connector/internal.rs

AuditOne has announced the [issue](https://github.com/AuditOneAuditReviews/AuroraEngine-Audit-Review/issues/18) in terms of migrating data before splitting the etc-connector logic. 
No changes in performance.
The test for that doesn't look trivial.

fix: do not require running contract in ft_resolve_transfer

---

engine-tests/src/tests/erc20_connector.rs
engine-workspace/src/contract.rs
engine-workspace/src/operation.rs
engine/src/contract_methods/connector/internal.rs
engine/src/contract_methods/connector/mod.rs
engine/src/lib.rs

The PR adds a public method to the engine/internal connector to get balances of multiple accounts. This is needed because we have changed the migration logic to migrate the balances based on the on-chain data, not off-chain.
The borsh is used instead of JSON to decrease gas usage and migrate more accounts in one batch.
Added a test to the crate `aurora-engine-tests`, not `aurora-engine-tests-connector` because the second one is enabled just for silo builds.
It's controversial whether to use `HashMap<AccountId, Balance>` or `Vec<(AccountId, Balance)>`; the `HashMap` prevents duplication, but on the other side, it increases gas usage.

feat: add api to get ft balances for multiple accounts

---

engine-tests/src/utils/mod.rs

Extended `ExecutionProfile` with logs for tests. 
Changes related only to `engine-tests` and do not affect main contract.
To profile NEAR contract execution flow it's convenient to debug.

Feat: extend `ExecutionProfile` with logs for tests

---

engine-standalone-storage/src/lib.rs

The PR extends the standalone storage API by adding two new methods, `set_custom_data` and `get_custom_data`, which allow saving and retrieving arbitrary data outside the crate. This allows us to use storage not only for storing blocks and transactions.

feat: extend standalone storage api

---

engine-precompiles/src/lib.rs
engine-precompiles/src/xcc.rs
engine-standalone-storage/src/engine_state.rs
engine-standalone-storage/src/lib.rs
engine-standalone-storage/src/relayer_db/mod.rs
engine-standalone-storage/src/relayer_db/types.rs
engine-standalone-storage/src/sync/types.rs
engine-transactions/src/lib.rs
engine/src/contract_methods/connector/deposit_event.rs
engine/src/lib.rs

A set of minor changes and clean-ups for overall codebase.
No changes should affect gas cost. 
Automated tests
Patches are minor and do not introduce any behaviour changes

chore: a set of minor improvements for engine

---

engine-tests-connector/src/utils.rs
engine-tests/src/tests/erc20_connector.rs
engine-tests/src/utils/workspace.rs
engine/src/contract_methods/connector/errors.rs
engine/src/contract_methods/connector/internal.rs
engine/src/errors.rs

Add the possibility of pausing the ft transfers for the internal eth-connector; this is needed to avoid pausing the whole Aurora engine during migration.
A new flag, `PAUSE_FT`, has been added that pauses all the public methods that could change the internal balances of the eth-connector token [`ft_transfer`, `ft_transfer_call`, `storage_deposit`, `storage_unregister`].
Some tests have been added to test the pause and unpause logic.

feat: pause FT transfers

---

engine-tests-connector/src/connector.rs
engine-tests-connector/src/utils.rs
engine-tests/src/utils/workspace.rs

The changes in the PR unpause all features of the eth connector since they are now paused after initialization by default.

fix: unpause eth connector after init in tests

---

engine-types/src/parameters/engine.rs
engine/src/contract_methods/admin.rs

The PR's motivation is to add the possibility of setting the amount of gas for the state migration in the `upgrade` transaction. This allows us to upgrade Aurora via a controller contract. With the previous amount of gas for the state migration (100 TGas), we can't do it because 200 Tgas is insufficient for the upgrade procedure via a controller. If we need more than 50 TGas for the state migration, we can call the `upgrade` transaction directly.

feat: provide amount of gas for state migration in upgrade

---

README.md

The `test` task is duplicated in the README.

chore(docs): remove duplicate `test` task

---

engine-types/Cargo.toml

`It's` (possessive) rather than `Its`.

chore: fix grammar in `Cargo.toml`

---

engine/src/contract_methods/connector/mod.rs
engine/src/engine.rs

After some investigation, we realised that the problem was caused by a change in gas costs after switching to near protocol version 66. The change relates to the amount of gas used to load contract data, which was [changed](https://github.com/near/nearcore/blob/master/core/parameters/res/runtime_configs/66.yaml#L15) from 216750 to 1089295 Gas per byte. The change increases the amount of gas used in the `mirror_erc20_token_callback` to approximately to 1TGas. So, more than 5TGas is needed now. Thanks to @birchmd for his help with this investigation.
There are no changes in the performance.
#950 bumps `near-workspace` to 0.12, which contains updated `near-sandbox` 2.1.1. on which the error is reproduced.
Check that the problem no longer reproduces after this commit is included in #950.

fix: exceeded prepaid gas error in mirror_erc20_token

---

.github/workflows/scheduled_lints.yml
.github/workflows/tests.yml
Cargo.lock
Cargo.toml
engine-tests/src/tests/erc20_connector.rs
engine-workspace/src/node.rs
scripts/build-neard-sandbox.sh

The motivation for adding this PR is the potentially incontinent behaviour of the Aurora contract on-chain and in our tests, due to the outdated version of the `neard-sandbox` that could be used in the `near-workspaces`. The PR adds a script that builds an actual version of the `neard-sandbox` for each network (mainnet and testnet) for use in the scheduled tests in the Github CI. The PR fixes the `test_exit_to_near_wnear*` tests that started failing after the near-workspace was bumped to 0.12 (near-sandbox 2.1.1).

ci: build neard-sandbox corresponding release version

---

.github/workflows/builds.yml
.github/workflows/lints.yml
.github/workflows/tests.yml
Cargo.lock
Cargo.toml
engine-tests/src/benches/nft_pagination.rs
engine-tests/src/tests/erc20.rs
engine-tests/src/tests/modexp.rs
engine-tests/src/tests/multisender.rs
engine-tests/src/tests/one_inch.rs
engine-tests/src/tests/promise_results_precompile.rs
engine-tests/src/tests/repro.rs
engine-tests/src/tests/sanity.rs
engine-tests/src/tests/standard_precompiles.rs
engine-tests/src/tests/uniswap.rs
engine-tests/src/tests/xcc.rs
engine-tests/src/utils/mocked_external.rs
engine-tests/src/utils/mod.rs

After switching to the new version of the `near-vm-runner` we can see increased consumption of the NEAR gas almost in every test. The reason is expected since the amount of gas per byte of loaded contract was [increased](https://github.com/near/nearcore/blob/master/core/parameters/res/runtime_configs/66.yaml#L15) from `216750` to `1089295`. In our case it's `1220709 * 1089295` instead of `1220709 * 216750` where the difference is `1065123534405 Gas` or `1,07 TGas`. 
NEAR gas consumption was increased for obvious reasons.

deps: bump near dependencies in the tests

---

.github/workflows/scheduled_lints.yml

The PR adds Slack notifications in case of failure of scheduled tasks.

ci: add slack notification of failure scheduled checks

---

.github/workflows/tests.yml
engine-standalone-storage/src/sync/mod.rs
engine-standalone-storage/src/sync/types.rs
engine-tests/src/lib.rs
engine-tests/src/tests/access_keys.rs
engine-tests/src/tests/erc20_mirror.rs
engine-tests/src/tests/one_inch.rs
engine-tests/src/utils/one_inch/liquidity_protocol.rs
engine-tests/src/utils/one_inch/mod.rs
engine-workspace/src/contract.rs
engine-workspace/src/lib.rs
engine/src/contract_methods/admin.rs
engine/src/contract_methods/connector/internal.rs
engine/src/engine.rs
engine/src/lib.rs

The PR fixes the vulnerability, which allows the removal of the full access key from the engine's account ID. 
No performance chages.
The corresponding test has been added.
Thanks to @mitinarseny for pointing it out.

fix: add relayer function call key vulnerability

---

.github/workflows/scheduled_lints.yml

The new js dependency `secp256k1@4.0.4` required node >= 18.x.x.

ci: bump node in scheduled lint task

---

Cargo.lock
Cargo.toml
Makefile.toml
engine-hashchain/src/hashchain.rs
engine-sdk/src/types.rs
engine-standalone-storage/src/lib.rs
engine-tests/src/lib.rs
engine-tests/src/tests/standalone/tracing.rs
engine/src/engine.rs
engine/src/lib.rs
etc/tests/benchmark-contract/src/lib.rs
rust-toolchain

The PR changes the usage of the nightly rust to the stable 1.81.0.
There are no changes in the performance.
No needed.
The `#[inline]` attribute has been removed from the `aurora_engine_std::types::keccak` function because there are some changes in linking. With the attribute, the function `keccak` is not available in the `aurora-engine-hashchain` crate.

feat: use stable 1.81.0 rust

---

engine-precompiles/src/native.rs
engine-precompiles/src/xcc.rs
engine-standalone-storage/src/sync/types.rs
engine-types/src/account_id.rs
engine/src/contract_methods/xcc.rs
engine/src/xcc.rs

The PR introduces some optimisations to the creation methods of the `AccounId` struct. Namely, it gets rid of redundant heap allocations.
There is no changes in the performance.
The existing tests cover the changes.

chore: add some optimisations to the AccountId creation methods

---

Cargo.lock
Cargo.toml
engine-precompiles/src/lib.rs
engine-precompiles/src/native.rs
engine-tests/src/tests/erc20_mirror.rs
engine-tests/src/tests/sanity.rs
engine-types/src/types/mod.rs
engine/src/engine.rs

The PR introduces changes to the `exitToNear` precompile, which allows the withdrawal of tokens via the OMNI bridge.
There is no performance changes.
Added tests for parsing new type of incoming arguments.

feat: adapt the exitToNear precompile to be compatible with OMNI bridge

---

Cargo.lock
Cargo.toml
engine-precompiles/Cargo.toml
engine-precompiles/src/secp256k1.rs
engine-sdk/Cargo.toml
engine-sdk/src/lib.rs
engine-tests/src/tests/uniswap.rs
engine-transactions/Cargo.toml
engine-transactions/src/eip_1559.rs
engine-transactions/src/eip_2930.rs
engine-transactions/src/legacy.rs

The PR moves the `ecrecover` implementation for not contract build (engine-standalone) to the `aurora-engine-sdk` crate. This change allows us to get rid of the `aurora-engine-precompiles` dependency in the `aurora-engine-transactions` crate. 
No performance chaanges.
Use existing tests.

chore: move ecrecover implementation to aurora-engine-sdk

---

CHANGES.md
Makefile.toml
engine-standalone-storage/src/sync/mod.rs
engine-standalone-storage/src/sync/types.rs
engine-tests/src/tests/erc20_mirror.rs
engine-tests/src/tests/one_inch.rs
engine-tests/src/tests/promise_results_precompile.rs
engine-tests/src/tests/repro.rs
engine-tests/src/tests/silo.rs
engine-tests/src/tests/standard_precompiles.rs
engine-tests/src/tests/uniswap.rs
engine/src/contract_methods/connector/mod.rs
engine/src/contract_methods/silo/mod.rs
engine/src/contract_methods/silo/whitelist.rs
engine/src/engine.rs
engine/src/lib.rs

The PR makes some changes to the Silo (VC) mode:
1. The mirroring of the ERC-20 tokens doesn't require enabling the silo mode.
2. White lists work in any mode, but they are disabled by default. 
3. Intoduced a transaction for setting white list statuses by one transaction.
4. Inrodused a view method which returns statuses of all whitelists.
Tiny NEAR gas consumption is increased because there is an additional check introduced. 
The corresponding tests have been modified.

feat: rework the logic related to the silo mode

---

engine-precompiles/src/native.rs

The PR rollbacks backward compatibility in the `exit_to_near` precompile. In the previous version, we didn't drop an error in the case when a user adds the suffix `unwrap` for withdrawing non-wNEAR tokens.

fix: rollback backward compatibility in exit_to_near precompile
